### ISSUE TITLE
When US visitors visit an Alaveteli site it should banner advertise both Muckrock (for national requests) and Alaveteli for new state and local deployments

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/alaveteli#1078]

**Comment by juanmartin** [comment]
Hi, sorry to bump this, but we're seeing this ad from Muckrock here in Argentina because of our ISP's routing I guess.
This can be seen as an announcement in the site (without adblock) but it isn't present in the announcement panel so we can't remove it. Is it hidden somewhere else in the core Alaveteli code? how can we remove it? 
Thanks and Cheers!

**Comment by garethrees** [comment]
Hey @juanmartin,

You are correct, it's not an admin-editable "Announcement".

The banner is [rendered](https://github.com/mysociety/alaveteli/blob/0.38.3.0/app/views/layouts/default.html.erb#L57-L58) [through javascript](https://github.com/mysociety/alaveteli/blob/0.38.3.0/app/assets/javascripts/general.js#L17-L36) by calling a [controller action](https://github.com/mysociety/alaveteli/blob/0.38.3.0/app/controllers/services_controller.rb#L8) that looks through some [hard-coded mappings](https://github.com/mysociety/alaveteli/blob/0.38.3.0/lib/world_foi_websites.rb) of countries to platform.

You could either remove the [`<div>`]((https://github.com/mysociety/alaveteli/blob/0.38.3.0/app/views/layouts/default.html.erb#L57-L58)) from the layout, or override the JavaScript, or I guess make the controller return something more appropriate.

I note that we don't list Argentina in these mappings. Is https://derechoaldato.com.ar/ your install?

**Comment by juanmartin** [comment]
Hey Gareth, thank you for your time.

> The banner is [rendered](https://github.com/mysociety/alaveteli/blob/0.38.3.0/app/views/layouts/default.html.erb#L57-L58) [through javascript](https://github.com/mysociety/alaveteli/blob/0.38.3.0/app/assets/javascripts/general.js#L17-L36) by calling a [controller action](https://github.com/mysociety/alaveteli/blob/0.38.3.0/app/controllers/services_controller.rb#L8) that looks through some [hard-coded mappings](https://github.com/mysociety/alaveteli/blob/0.38.3.0/lib/world_foi_websites.rb) of countries to platform.

Can I just comment this line out?
`$('body:not(.front) #locality-popup').show()`

We wouldn't mind the issue because it promotes other FOI sites but it is weird since it gets to be shown to visitors from Argentina, it seems our cellular network has some kind of proxy in the US so our site picks local users as US visitors. It does not happen with my home connection, only cellular.

Feature request maybe? showing/hiding this could be an option in the admin panel. I would commit a PR but my Ruby skills are close to null.

> I note that we don't list Argentina in these mappings. Is https://derechoaldato.com.ar/ your install?
Yup!! it is! we would be glad to be added to the list of Alaveteli instances around the world.

Thanks again

**Comment by garethrees** [comment]
> Can I just comment this line out?
> `$('body:not(.front) #locality-popup').show()`

Looks like it _should_ work, but I haven't tested.

If it doesn't work, try posting what you've tried and the error you're seeing to the [developers mailing list](https://alaveteli.org/community/).

> Feature request maybe?

We try to avoid too many configuration options – overriding is the best way to deal with this.

Might be related to out of date geoip databases; we have it on our list to migrate to the "official" tool so that updates are easier https://github.com/mysociety/alaveteli/issues/5550.

> Yup!! it is! we would be glad to be added to the list of Alaveteli instances around the world.
> 
> Thanks again

Done! 874998e87
