### ISSUE TITLE
Allow users to Modify their own annotations

### ISSUE THREAD

**Issue by benrfairless** [mysociety/alaveteli#1451]
https://github.com/openaustralia/righttoknow/issues/322 - Requested by one of our users who wanted to add more information to their annotation

I would suggest
- A clearly defined flag on any annotations to show they have been edited
- A way for Admins to see what changes have been made and to revert any changes
- The ability to disable this option for users who misbehave with it.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mysociety/alaveteli/issues/1451#issuecomment-2485774117

@HelenWDTK, https://github.com/mysociety/alaveteli/issues/8643#issuecomment-3249224801 constitutes the "discussion" desired.

**Comment by garethrees** [comment]
Couple of additional requests made in https://github.com/mysociety/alaveteli/issues/8643.

Since both of these we've added the ability to limit comments/annotations to users only making them on their own requests, and have used this option in WhatDoTheyKnow. That's to say, this is more of a side feature that we're not really focused on at the moment, and we have no plans to work on this in the foreseeable future. Also, given its relatively occasional that we'd want this, I don't think it's really worth adding more to the codebase for a pretty low value feature.

That said, if someone really wanted to contribute a PR then would be happy to help shape up the plan for how this would work.
