### ISSUE TITLE
Don't call it a disclaimer

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/alaveteli#2041]
All or almost of the text in the current 'disclaimer' in outgoing emails isn't really about disclaiming responsibility. I think calling it a 'disclaimer' might make some people less likely to read it.

I suggest that the text should be split into two sections.  The heading for the first section should read "Important information about replies to this email" and the second heading should read "More information about WhatDoTheyKnow.com".

**\* current text ***

```
“-------------------------------------------------------------------
Disclaimer: This message and any reply that you make will be published on the internet. Our privacy and copyright policies:
http://www.whatdotheyknow.com/help/officers
Please use this email address for all replies to this request: request-*****-********@whatdotheyknow.com
Is CIO-FOI@mod.uk the wrong address for Freedom of Information requests to Ministry of Defence? If so please contact us using this form:
http://www.whatdotheyknow.com/help/contact
If you find WhatDoTheyKnow useful as an FOI officer, please ask your web manager to suggest us on your organisation's FOI page
-------------------------------------------------------------------” 
```

Source: https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/302754/20120925-CN13-HandlingRequestsfrom_Whatdotheyknow.pdf

**Comment by TomSteinberg** [comment]
I think it could be worth trying to see how short you could make it. For example:

----
IMPORTANT - Your reply will be published automatically online, on WhatDoTheyKnow.com

To learn about the many steps we take to make this site helpful for FOI officers, see http://Whatdotheyknow.com/helpfulpage
----

Then put everything else on that link page...

**Comment by RichardTaylor** [comment]
I suggest keeping:
>Please use this email address for all replies to this request: request-*****-********@whatdotheyknow.com

The reason is so we can say requesters have expressed a clear preference for getting their response via that email address.  Section 11 of the Freedom of Information Act requires public bodies to take account of a requestors preference as to how they want their response communicated. I interpret this as meaning if a request says please respond via the WDTK address given the authority really should do so.

http://www.legislation.gov.uk/ukpga/2000/36/section/11

[Others interpret that section differently and doesn't actually say quite what I'd like it to say - but I think the essence is there]

**Comment by RichardTaylor** [comment]
You could argue it's obvious when you send an email you want the response to go to the address the email came from (or the reply-to address if any); so perhaps that line isn't really needed if we're looking to keep things simple.

**Comment by confirmordeny** [comment]
closed as not planned and no clear consensus has emerged on approach
