### ISSUE TITLE
Add physical address and opt-in/opt-out instructions

### ISSUE THREAD

**Issue by Flupsy** [mysociety/alaveteli#2430]
Please add
- [ ] a physical address to the 'contact' page
- [ ] opt-out (i.e. unsubscribe) instructions to the 'privacy' page. (blocked by https://github.com/mysociety/alaveteli/issues/4603)

This is so that Returnpath can certify outbound WDTK mail to make it more resilient to overzealous spam filters.

**Comment by garethrees** [comment]
@sagepe do we care about this now? I think we lumped this in with [GDPR](https://github.com/mysociety/alaveteli/milestone/51) because of https://github.com/mysociety/alaveteli/issues/4603, but we no longer use ReturnPath so I don't think this is a _requirement_ of GDPR. Closing by default, but reopen if you think necessary.
