### ISSUE TITLE
Render multiple newlines in incoming message as paragraphs not linebreaks

### ISSUE THREAD

**Issue by zarino** [mysociety/alaveteli#3318]
Not sure whether this is part of #707 or a new thing.

It feels like every official reply I see on WDTK has double spacing between the sentences / paragraphs. It  reduces information density, makes the page needlessly long, and makes it hard to scan for important bits of the reply.

We present the user's original message as paragraph tags (`</p><p>`) but official replies are just a single paragraph with double (and triple!!) linebreaks inside (`<br><br><br>`). Why?

![screen shot 2016-06-14 at 07 30 58](https://cloud.githubusercontent.com/assets/739624/16033198/9cc2ab92-3202-11e6-80ec-8f663e0bf335.png)

**Comment by garethrees** [comment]
#707 is referring to _outgoing_ messages, (i.e. sent by an Alaveteli user rather than the authority), but yeah, its the same problem. https://github.com/mysociety/alaveteli/commit/1a0626aea04455bd19a31b5f63fe0473b8465f9b introduced [`simple_format`](http://api.rubyonrails.org/v3.2.13/classes/ActionView/Helpers/TextHelper.html#method-i-simple_format) for outgoing messages. Need to apply it to [`IncomingMessage#get_body_for_html_display`](https://github.com/mysociety/alaveteli/blob/d008384/app/models/incoming_message.rb#L610-L653). Changing the title of this issue to reflect this.

**Comment by RichardTaylor** [comment]
The Met Police have queried how some of the text in their latest responses is being shown on WhatDoTheyKnow writing:

> there is double spacing between paragraphs ... which is not appropriate.
>The screen shots clearly highlight the double spacing between paragraphs issue.

An example of the issue  given is at:

https://www.whatdotheyknow.com/request/information_on_meetings_with_cou_2#incoming-1296208

It looks perfectly readable to me, but there are perhaps more line breaks than might be expected. The issue is manifesting itself in the same way as the issue described in the initial issue description on this ticket.

**Comment by mdeuk** [comment]
> The Met Police have queried how some of the text in their latest responses is being shown on WhatDoTheyKnow writing:
> 
> > there is double spacing between paragraphs ... which is not appropriate.
> > The screen shots clearly highlight the double spacing between paragraphs issue.
> 
> An example of the issue given is at:
> 
> https://www.whatdotheyknow.com/request/information_on_meetings_with_cou_2#incoming-1296208
> 

I am almost certain this instance is occurring as a result of a peculiar user error - it does not appear to be caused by Alaveteli, as,  the issue is, in fact, present in the raw message itself.

Looking at the raw message, the plain text version is being rendered with three line breaks between each paragraph… 
<img width="500" alt="screenshot 2019-02-01 at 8 17 36 pm" src="https://user-images.githubusercontent.com/249418/52147496-cbd49a00-265e-11e9-8af9-a1ea29286f9a.png">
(for ease of reference I have added numbers to each of the line breaks)

This isn't obvious so obvious if you open the raw message in an email client that can render rich text / HTML,  as, for all intents and purposes, the message is displayed exactly as the user would intend; however, the underlying HTML shares a similar flaw.

Typically, you would expect each paragraph to be broken apart using the standard HTML paragraph tags; however, in this instance, each paragraph is being closed (as expected), but, rather than the next paragraph following, there is actually two sets of paragraph tags which would, to some extent, explain the rather curious plain text render, as, in effect, Outlook is rendering based on what it is perceiving to be the user's intended behaviour.

<img width="1107" alt="screenshot 2019-02-01 at 8 36 29 pm" src="https://user-images.githubusercontent.com/249418/52148333-3edf1000-2661-11e9-88ff-8e66fefd2e16.png">
In the above example (which is a rendered copy open in Apple mail) you can (just about) see the issue in the HTML - the paragraph break that its highlighted is actually composed of one paragraph which has a very narrow line spacing (red arrow), followed by a second paragraph at the regular spacing (orange arrow).

This is consistent throughout the message (save for the email disclaimer), therefore, I would conclude it is a user/client issue.

**Comment by garethrees** [comment]
Yeah, this is probably something they're doing but we should be able to handle it, so I've opened https://github.com/mysociety/alaveteli/issues/5092.
