### ISSUE TITLE
Improve reporting and taking down a request

### ISSUE THREAD

**Issue by kat** [mysociety/alaveteli#3357]
Make the process of reporting and taking down a request more like suggesting and adding a new authority

(from discussion with @henare)

**Comment by garethrees** [comment]
Hey Kat,

Could you explain a little more about what you'd like to be able to do that you can't now?

From the user's perspective, the forms seem fairly similar:

![screen shot 2016-07-04 at 09 48 15](https://cloud.githubusercontent.com/assets/282788/16555458/a3ce5330-41cc-11e6-910f-42ba692de7cf.png)

![screen shot 2016-07-04 at 09 48 32](https://cloud.githubusercontent.com/assets/282788/16555467/a7b3bac6-41cc-11e6-8365-cba779cad793.png)

It looks like you can do a little more through the admin summary page for authority change requests:

![screen shot 2016-07-04 at 09 46 04](https://cloud.githubusercontent.com/assets/282788/16555476/b2372b40-41cc-11e6-8bc0-92a3fca542d1.png)

I think that reviewing a reported request might be a little more difficult on the admin summary page because there might be a lot more information to consider – the request may have multiple messages and comments.

There are also several actions that you might take for a reported request:

- Change the request visibility
- Add a censor rule
- Stop comments
- Stop incoming mail
- Resend a failed outgoing message

Maybe we could cover some common cases on the summary page, but it would be difficult to account for every action you might want to take.

Let us know what you're thinking.

Cheers!

**Comment by garethrees** [comment]
Related to https://github.com/mysociety/alaveteli/issues/419?

**Comment by henare** [comment]
Almost all of our reports are from people reporting requests for, or containing, personal information. It would be great if the admin could very easily hide a request when it's reported. I would also be good for Alaveteli to email the person thanking them for reporting the request and telling them that we've hidden it (like the add authority one does) so they know we've done something (and they feel happy knowing they've made a difference).

**Comment by garethrees** [comment]
Think everything here is covered now that https://github.com/mysociety/alaveteli/issues/3543 is fixed
