### ISSUE TITLE
Help people avoid making a blank search for an authority

### ISSUE THREAD

**Issue by equivalentideas** [mysociety/alaveteli#3458]
The most common search (1 in 20) on [Right To Know’s Select Authority page](https://www.righttoknow.org.au/select_authority) is [a blank search](https://www.righttoknow.org.au/select_authority?utf8=%E2%9C%93&query=&bodies=1&commit=Search).

Are the other sites seeing this as well? Why is this happening?

Would it be helpful to users to prevent a reload and suggest they enter a term if searching is there intention (using the simple `required` attribute on the field)? e.g.
![screen shot 2016-08-15 at 4 44 11 pm](https://cloud.githubusercontent.com/assets/1239550/17657531/8ce73568-6307-11e6-9dc2-713aaf932a30.png)

**Comment by zarino** [comment]
Adding a `required` attribute will certainly prevent blank searches.

I also wonder whether there should be a `<label>` above the input, telling you what to type? (In fact, the `<label>` is already there, but hidden – I wonder why?)

**Comment by garethrees** [comment]
> Adding a `required` attribute will certainly prevent blank searches.

+1

> I also wonder whether there should be a `<label>` above the input, telling you what to type? (In fact, the `<label>` is already there, but hidden – I wonder why?)

I guess the placeholder covers that:

![screen shot 2016-10-11 at 11 17 16](https://cloud.githubusercontent.com/assets/282788/19267030/64e10458-8fa4-11e6-8dfc-d1b8315757a9.png)

**Comment by zarino** [comment]
@garethrees: I wouldn’t be surprised if a significant chunk of visitors skip right over that “First, type in…” sentence, and then either mistake the placeholder text for a pre-filled input (the text colour is fairly dark) and click "Search" because they want to query the Department of Health, or mistake the placeholder text as exactly what it appears, just an example of something to search for, and mistakenly click "Search" expecting to be shown a thing that will let them begin a search.

**Comment by equivalentideas** [comment]
Would a question to frame this initial step be a good label? e.g. “Who would you like to request documents from?”, “Who is your request to?”, etc. Then maybe move the explanation text (“by law they have to respond”) underneath the input. Is that text important for users?

**Comment by garethrees** [comment]
I don't have any evidence to support this, but I prefer that we _tell_ the user what to do ("Find an authority") rather than asking them a question that might not translate so well to other languages.


The quickest win here would be to add the `required` attribute.


For extra points we could improve the prominence of the search form, but this is a bit better in the newer Alaveteli theme.

![screen shot 2016-10-17 at 10 23 32](https://cloud.githubusercontent.com/assets/282788/19432289/ea4be67c-9453-11e6-8e88-4cef40981275.png)

For the RTK theme you could try adding a background to the search form so that the white form field stands out more from the white background?

![screen shot 2016-10-17 at 10 27 56](https://cloud.githubusercontent.com/assets/282788/19432445/7e22322a-9454-11e6-8124-37509d64c0dc.png)
