### ISSUE TITLE
Users not given access to log files when request has been re-sent

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/alaveteli#3478]
![ss 2016-09-10 at 12 38 01](https://cloud.githubusercontent.com/assets/11923618/18410206/9416f1c4-7753-11e6-8851-06423da21a92.png)
We sometimes re-send a request if there's been a delivery problem. We may re-send to the same address if we think the request email hasn't been successfully received due to a transient problem with the authority's email system, but more often we correct the out of date email address in the authority's record and re-send to the new email address.
The note put on the request page when we do this, as above, doesn't have the green tick symbol in the top right corner and so doesn't afford the requester access to the email logs showing whether or not the email has been successfully received by the public authority's email server.
It would be great if access to the relevant log lines could be extended to such notes, as the presence of such a note generally means there's been a previous delivery problem and the user is therefore probably more likely to want to see the log file lines for the attempted re-delivery.
Thank you

**Comment by garethrees** [comment]
They appear in the logs of the original message:

![screen shot 2016-09-12 at 09 42 10](https://cloud.githubusercontent.com/assets/282788/18429786/39917438-78cd-11e6-879c-d60b14957178.png)

I guess this is a bit confusing. The technical reason is that the "Outgoing Message" database record is the same, so mail logs are just attached to that message. Off the top of my head, I don't think it would be trivial to split these out.

What we _could_ possibly do is add the initial outgoing message's delivery status to a resent bubble so that while they're duplicated, you'd be able to get at the logs in the context of where you are on the page. This in itself might get confusing though. In the case of a _failed_ delivery, the "resent" bubble would get a "failed" status until we get the logs back from the (hopefully successful) resend.
