### ISSUE TITLE
Statistics page is very long

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#3646]
The body significantly extends beyond the footer. https://www.whatdotheyknow.com/statistics

**Comment by lizconlan** [comment]
For some reason `<table class="visually-hidden>` under Number of request hide events over time is 27400 pixels tall and is affecting the height of the page.

**Comment by garethrees** [comment]
Yeah I'd say its likely to be something to do with it not getting resized after converting the text-stats to the JS chart.

**Comment by lizconlan** [comment]
Ah, the table is supposed to be shown when JS is disabled. In a perfect world needs borders otherwise it's hard to read. (so getting JS to apply `display: none` should be fine - adding gridlines at the same time would be great!)

Looks like we missed this as the table only gets long enough to make a strong visual difference to the page when there's a lot of data.

**Comment by lizconlan** [comment]
ah, for some reason `<table>` isn't being treated as a block level element so `height: 1px` isn't being applied
