### ISSUE TITLE
Only show alternative followup addresses if there are many

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#426]
When clicking "send a follow up" on my request at http://www.whatdotheyknow.com/request/electronic_case_file_sharing_cps I got the following which doesn't make any sense:

> Don't want to address your message to the main FOI contact at Ministry of Justice? You can also write to:
> 
>
> * the main FOI contact address for Ministry of Justice

**Comment by garethrees** [comment]
Linking to https://github.com/mysociety/alaveteli/issues/4354

**Comment by garethrees** [comment]
We shouldn't show this if there's only one address to reply to. Renamed this issue to reflect the required action.

Interestingly, we do have a count conditional, so maybe this just needs to change to `> 1` instead of `> 0`:

https://github.com/mysociety/alaveteli/blob/1699d74013547e9c7958e5cac6dd3657cd27bb9d/app/views/followups/_followup.html.erb#L23-L47

**Comment by lizconlan** [comment]
> maybe this just needs to change to `> 1` instead of `> 0`

Not quite - turns out there's a difference between adding a followup where there's no other correspondence and when you're effectively replying to a response...

If there's no incoming message, we run `who_can_followup_to(nil)`and return the main contact address; (count = 1)

If there is an incoming_message, then it's `who_can_followup_to(last_incoming_message)` which returns...
* count = 0 if the response is from the main contact email
* count = 1 if the response is from an individual (to present the main contact address as an alternative to replying to an individual account)

**Comment by lizconlan** [comment]
oh also - note to implementer (currently me), this template is overridden in wdtk-theme
