### ISSUE TITLE
Trying to access localhost:11211 in production

### ISSUE THREAD

**Issue by lizconlan** [mysociety/alaveteli#4281]
Could be fragment caching related or related to #4280 

`WARN -- : localhost:11211 failed (count: 2) Errno::ECONNREFUSED: Connection refused - connect(2)`

This looks like an attempt to access memcache on a server which does not have memcache set up.

Often occurs before or after a fragment cache Read or Write line but that might be coincidental

**Comment by garethrees** [comment]
First questions:

- [ ] Is memcached installed?
- [ ] Is memcached running?

**Comment by garethrees** [comment]
Hey @schlos,

@lizconlan had a look in to this and by the looks of it, you don't have memcached installed/running.

You can resolve this by:

```
sudo apt-get install memcached
sudo service memcached start
```

I've added some notes to the [changelog](https://github.com/mysociety/alaveteli/commit/0f2de00e057e6e70a79c953bab7661d98cdaa963) so that others don't get caught out by this.

I'll close this assuming that the above commands fix that problem, but do reopen if the above doesn't make that error disappear.

**Comment by schlos** [comment]
Thanks, I've installed memcached, seems it was not installed. I'll monitor and let you now if it will be reproducible again.

Cheers!
