### ISSUE TITLE
Improve the user experience of replying to your own request

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/alaveteli#4354]
It feels a bit old-fashioned to not be able to write your reply inline on the request page, more like a comment thread.

Currently if you choose to reply it sends you to a new page (screenshot below). 
![www whatdotheyknow com-request-438329-followups-new-1053205](https://user-images.githubusercontent.com/2292925/32653516-11d07846-c600-11e7-9b2a-ac2c2232f1d0.png)

**Comment by garethrees** [comment]
Just a counter argument – an inline reply might make for shorter, less clear followups to authorities. I think this extra step does feel more like pulling out a new sheet of paper to write your next well considered letter.

**Comment by wrightmartin** [comment]
> Just a counter argument – an inline reply might make for shorter, less clear followups to authorities. I think this extra step does feel more like pulling out a new sheet of paper to write your next well considered letter.

That did cross my mind and could be bang on.

Either way, that page needs a bit of love from the design dept

**Comment by garethrees** [comment]
> Either way, that page needs a bit of love from the design dept

+1!

**Comment by garethrees** [comment]
Oh, that reminds me, an AskTheEU user recently had a bit of a problem sending an internal review. They'd mistakenly picked the "do-not-reply" address as the recipient rather than the main FOI contact. It is pretty confusing. https://groups.google.com/a/mysociety.org/d/msg/alaveteli/69YdYd6Fh2s/AcEDO1qhCQAJ

**Comment by garethrees** [comment]
I don't think inline replies are a quick win yet, but we can do a lot to improve this page:

  * Move reply form to the top of the page; put last message below the form
  * Pre-select "Anything else"
  * Use the default authority name for the salutation; don't bother with the name plucked from the From address – "its usually wrong".
  * Always use the default authority address for replies – let the authority triage it.

**Comment by wrightmartin** [comment]
Here's a redesign of this screen

- Change the recipient through a drop down - much more natural approach
- Check the box if it's an internal review request (rather than pre-selecting 'anything else' just make 'internal review' the exceptional choice)
- Show the previous reply above the message, but hide it behind a click, so you don't need to take up the space if the user doesn't require it



![desktop hd](https://user-images.githubusercontent.com/2292925/36157229-41c1ae96-10d1-11e8-9908-ec6fb9170942.png)

**Comment by garethrees** [comment]
See also comments in https://github.com/mysociety/alaveteli/issues/1049

**Comment by garethrees** [comment]
We should also consider https://github.com/mysociety/whatdotheyknow-theme/issues/372 here.

**Comment by zarino** [comment]
A few notes to self:

* The markup for this is all in `views/followup/_followup.html.erb`
* The page serves both public and private requests (using slightly different wording, via partials like `alaveteli_pro/followups/_embargoed_form_title.html.erb`) so that’s something to keep an eye out for
* whatdotheyknow-theme, of course, has its own version of `views/followup/_followup.html.erb`, but only so that it can:
   * change the "if you are dissatisfied" URL from `/help/unhappy` to `http://www.foiwiki.com/…`
   * add an "in term time" qualifier to the "response overdue" help text if the authority is a school

**Comment by WilliamWDTK** [comment]
As [noted](https://github.com/mysociety/alaveteli/issues/5441#issuecomment-2240079872) on #5441, a user has suggested using "a user friendly visible (colour coded) S.M.A.R.T page".

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
