### ISSUE TITLE
How to add unique request url to each email footer?

### ISSUE THREAD

**Issue by aliteralmind** [mysociety/alaveteli#4402]
What is the variable of the url to the request's unique webpage? We would like to add this to the footer of EVERY email. We are currently unsure how to do this.

This is critical in order to give records custodians a way to see the bigger picture. It also would allow followups to be sent as reminders, without having to duplicate the entirety of the original request-text (or manually having to obtain and paste the url into the body).

Otherwise, extremely happy users! Thanks.

**Comment by garethrees** [comment]
Hey @aliteralmind.

The main thing you need is the `request_url` helper. You can pass an `InfoRequest` instance to it, so for example: `request_url(@info_request)`.

Note that Rails generates `*_path` and `*_url` helpers – in mailers you need to use the `*_url` version so that the domain part of the URL is included.

The main place you'll want to look is [`OutgoingMailer`](https://github.com/mysociety/alaveteli/blob/0.30.0.1/app/mailers/outgoing_mailer.rb#L16-L40). The `#initial_request` and `#followup` methods are the main things that send mail to authorities.

We've already set `@info_request` in both of these, so it will already be available to the mail templates in [`app/views/outgoing_mailer`](https://github.com/mysociety/alaveteli/tree/0.30.0.1/app/views/outgoing_mailer).

[`_followup_footer.html.erb`](https://github.com/mysociety/alaveteli/blob/0.30.0.1/app/views/outgoing_mailer/_followup_footer.text.erb) is actually rendered in to both of the templates, so that would probably be a [good place](https://github.com/mysociety/alaveteli/blob/0.30.0.1/app/views/outgoing_mailer/_followup_footer.text.erb#L1-L3) for your addition.

In the template, to render the URL you can add:

```erb
<%= request_url(@info_request) %> 
```

Let us know if there's anything you're unsure of. Happy to review a diff of the changes you make.

Hope that helps.

**Comment by garethrees** [comment]
I forgot to say, you should override the template in your theme.

We've done this for [WDTK](https://www.whatdotheyknow.com):  https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/outgoing_mailer/_followup_footer.text.erb#L5-L7

**Comment by garethrees** [comment]
I think this is resolved now, so closing

**Comment by gavinrozzi** [comment]
I've implemented it in this commit. Thanks for your detailed explanation, Gareth. @aliteralmind 
 let me know if you want me to make any other changes. https://github.com/gavinrozzi/opramachine-theme/commit/962e3489905ae446ef38155df973e69525b2b650
