### ISSUE TITLE
Should be able to unsubscribe from track emails without signing in

### ISSUE THREAD

**Issue by dracos** [mysociety/alaveteli#4551]
Currently there is an "Alter your subscription" link, which is a very high barrier to entry for an email subscription; you should not have to log in in order to stop getting an email.

**Comment by garethrees** [comment]
Is this causing a problem for our spam scores etc, or just an observation that its not ideal?

**Comment by dracos** [comment]
If someone is unable to unsubscribe smoothly, I imagine they will resolve the issue from their point of view by hitting their Spam button, yes - see the "Damned as spam" section of https://econsultancy.com/blog/69181-10-rules-for-getting-email-unsubscribes-right
It certainly makes it much harder for me to unsubscribe someone who's doing that reported to us through email provider feedback loops.

**Comment by garethrees** [comment]
I've renamed this to reflect a more meaningful step we can take on our way to https://github.com/mysociety/alaveteli/issues/4603.

At the moment, a user can only control whether they receive email notifications for emails generated by `TrackMailer` (controlled by `User#receive_email_alerts`).

We currently have an "Alter your subscription" link that requires the user to sign in:

![screen shot 2018-11-22 at 10 35 31](https://user-images.githubusercontent.com/282788/48897600-64ba8e00-ee42-11e8-8f1d-bea2395dabf0.png)

This allows a user to toggle email notifications, and remove any `TrackThings` that they no longer follow.

We should add an additional section to allow a user to toggle `receive_email_alerts` without signing in.

[Unsubscribe Links in Rails with `ActiveSupport::MessageVerifier`](http://ngauthier.com/2013/01/rails-unsubscribe-with-active-support-message-verifier.html) looks like a neat way of doing this.

At the end of this, we should have two options that look like:

```
Alter your subscription
=======================

https://www.whatdotheyknow.com/profile/sign_in?r=%2Fuser%2Fgareth_rees_3%23email_subscriptions

Turn off email alerts
=====================

https://www.whatdotheyknow.com/unsubscribe/BAhJIgtib3JrZWQGOgZFVA%3D%3D--977c57e2df4940f4fe6b6e44d1febad6582495be
```

Alter your subscription should behave as before.

Turn off email alerts should:

* Extract the user ID from the token
* Find the `User` record
* Set `User#receive_email_alerts` to `false` (always set to `false` – never toggle back to `true`)
* **Should not** sign in the user
* Show a message saying that we've turned off email alerts for things your following (with link to `/user/:url_name/profile#email_subscriptions` so that they can sign in if they wish)
* Show a message saying they'll still receive some email (like password reset, new response on request, etc)
