### ISSUE TITLE
Make creating multiple censor rules easier

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4626]
Often a series of censor rules are required to remove material from a request. Often an administrator will open up a series of tabs for new censor rules, and go through them populating the text to be replaced with eg. each line of text from a section of correspondence, and copy and paste standard replacement text eg. "[personal information removed]" and a reason eg. "removing accidentally released personal information" on each tab. 

This ticket is for reconsidering that workflow; possibly by enabling lots of censor rules to be created and edited on one page. 

See also #1156 on ineffective censor rules; this could help particularly with multi-line censor rules and #4625 on how comments/reasons for censor rules work.

**Comment by RichardTaylor** [comment]
In practice on WhatDoTheyKnow we tend to use often use the same replacements:

* [name removed]
* [personal information removed]
* [potentially defamatory material removed]
* [extraneous material removed]
* [extraneous and potentially defamatory material removed]

and the comment reasons often repeat too eg. 
* requested by user
* potential defamation
* accidental release of personal information


While a free text option is required, having some way to quickly deploy commonly used options might help; and more consistency might aid the generation of statistics so we can be more open about how we're running the site and how, and why, censor rules are used.

**Comment by RichardTaylor** [comment]
This is still an issue.

**Comment by garethrees** [comment]
We've now got canned replacements (https://github.com/mysociety/alaveteli/issues/6487) and dealing with comments (https://github.com/mysociety/alaveteli/issues/4625) has a path forward.

https://github.com/mysociety/alaveteli/issues/1156 I think covers the issue of making a single censor rule do the job of multiple.

So I think this is as easy as we can make it when we _do_ have to create multiple rules?

> possibly by enabling lots of censor rules to be created and edited on one page

We _could_ do this, but I'm not sure it adds that much value? Most of the time I check the presentation after every rule rather than adding a bunch and then checking afterwards.

**Comment by garethrees** [comment]
Closing as I think we've covered the gist of this issue via other issues.
