### ISSUE TITLE
[ERROR] sessions#new (ActionView::MissingTemplate) Missing template user/sign 

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#4670]
```
An ActionView::MissingTemplate occurred in sessions#new:

  Missing template user/sign with {:locale=>[:en], :formats=>["application/html"], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee]}. Searched in:
  * "/data/vhost/www.whatdotheyknow.com/alaveteli-2018-05-31T13-01-51/lib/themes/whatdotheyknow-theme/lib/views"
  * "/data/vhost/www.whatdotheyknow.com/alaveteli-2018-05-31T13-01-51/app/views"
  * "/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.3.0/gems/foundation-rails-5.5.3.2/app/views"

  app/controllers/users/sessions_controller.rb:23:in `new'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/profile/sign_in?token=j8wqp5jzwsmabs5zs2x
  * HTTP Method: GET
  * IP address : [FILTERED]
  * Parameters : {"token"=>"j8wqp5jzwsmabs5zs2x", "controller"=>"users/sessions", "action"=>"new"}
  * Timestamp  : 2018-06-09 14:36:30 +0100
  * Server : [FILTERED]
  * Rails root : /[FILTERED]/www.whatdotheyknow.com/alaveteli-2018-05-31T13-01-51
  * Process: 13917

-------------------------------
Backtrace:
-------------------------------

  app/controllers/users/sessions_controller.rb:23:in `new'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by lizconlan** [comment]
error occurs at: https://github.com/mysociety/alaveteli/blob/3d67e4697e0c98da2e0c5406b6f421dc2b768d7b/app/controllers/users/sessions_controller.rb#L23

**Comment by lizconlan** [comment]
There are no obvious code changes that would have caused this - and it's not what we initially thought/feared (a rarely travelled branch of the new spam handling code causing the `render :template` to be somehow sent as an `application` rather than a `text` request, or, from where the template's called, looking in the wrong folder path) as this error predates any of those changes.

And it doesn't look like it could be anything to do with a stale `PostRedirect` as that would cause a redirect away rather than dropping through to generate the error we see here in the last line of the action method.

The only way I can reproduce it is to deliberately send the request with `HTTP_ACCEPT: application/html` (which matches what we see in the expanded ENVIRONMENT detail of the error itself (not supplied here)). (In this case by messing with the `network.http.accept.default` string in Firefox [1].)

This exact form of the error seems to come from a single device running a [nearly 10 year old version of Firefox](https://website-archive.mozilla.org/www.mozilla.org/firefox_releasenotes/en-US/firefox/3.0.5/releasenotes/) on Windows Vista (or possibly Server 2008, which might explain an unusual config).

Closing as this looks like a (rare) browser config issue - or a handcrafted request - rather than a code issue.

---

[1] changing it (in Quantum) from the default `text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8` to `application/html`
