### ISSUE TITLE
More clearly identify hidden and requester_only requests on a user admin page

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4915]
Currently hidden / requester_only requests can only be identified if the ">" to expand the details is expanded and the prominence field for the request is reviewed. 

Marking hidden / requester_only requests clearly in the initial view might assist with running the site - for example by giving a clearer overview of a users' account - letting an administrator see at a glance if they are a problematic user for example. 

The solution could be just the words "hidden"/"requester only" presented as appropriate before the request title - which is a similar approach to that taken for annotations on a user page where the word "hidden" or "visible" appears in annotation's visible header line. 

Colour (red) could also be used to identify requests which are not visible to the public.

**Comment by RichardTaylor** [comment]
I still think this would be a useful feature. 

One additional use-case is identifying hidden requests when a user requests access to them, that's a form of subject access request we get occasionally. Such requests may be eliminated entirely by implementing the suggestion at #843 'Requests with prominance "requester_only" should appear on requestor's "My requests" page'.

**Comment by RichardTaylor** [comment]
As an enhancement to this feature request it might be good to have a flag where a request contains a hidden/requester_only message (or perhaps even where a censor rule has been applied too).

**Comment by garethrees** [comment]
Had a quick hack around with this. How does this feel?

![Screenshot 2021-03-24 at 17 17 12](https://user-images.githubusercontent.com/282788/112355199-56583780-8cc5-11eb-86d2-77c0c499a4ec.png)

I'm not sure about adding loads of text to the UI. This feels like quite a good balance.

Idea is that you can hover over to reveal the actual word (hard to screenshot, but YSWIM):

![Screenshot 2021-03-24 at 17 17 29](https://user-images.githubusercontent.com/282788/112355278-6708ad80-8cc5-11eb-9450-038a7c01be7e.png)

**Comment by garethrees** [comment]
Or maybe a little bolder?

![Screenshot 2021-03-24 at 18 04 50](https://user-images.githubusercontent.com/282788/112361602-7be83f80-8ccb-11eb-8d54-756b84174df0.png)

**Comment by RichardTaylor** [comment]
As having a hidden/backpaged/requester_only thread is rare I don't think we need to worry much about clutter. 

If no action is taken in the case of requests with a prominence of normal whatever change is made here will have no impact on all but a small minority of user admin pages. 

I think just the words hidden/backpaged/requester_only would be OK, and have the benefit of being intuitive. 

As for a clear symbol - the no-entry sign used on roads has widespread global use:
https://en.wikipedia.org/wiki/Prohibitory_traffic_sign#No_entry

however we probably want to distinguish between more than two states. 

The words visible or hidden are already used on the user admin page in relation to annotations so using words to describe request prominence would be consistent with that.

**Comment by garethrees** [comment]
Couple of different options:

**Text**

![Screenshot 2021-03-30 at 15 32 41](https://user-images.githubusercontent.com/282788/113006567-68c2ed00-916d-11eb-97af-0145d28155b7.png)

**Labels**

![Screenshot 2021-03-30 at 15 34 08](https://user-images.githubusercontent.com/282788/113006588-6d87a100-916d-11eb-93fc-2795f24ecf46.png)

**Labels at the end**

![Screenshot 2021-03-30 at 15 43 51](https://user-images.githubusercontent.com/282788/113008234-c60b6e00-916e-11eb-9890-bb2fdc29e213.png)

I didn't bother to colour the labels here since the drop-down onto the next line is totally off-putting.

---

Personally I prefer the eye icon, since it's unobtrusive enough when you're not looking at the prominence, but also stands out enough that if you see a column full of red or yellow you know you're dealing with a potentially problematic user. It also makes it easier to apply to other parts of the site where we use the eye icon to link to the public view of the request.

**Comment by RichardTaylor** [comment]
Just to note there have been a few occasions where this new feature has saved me some time. It has stopped me having to look through a users' requests one by one to see their prominence. 

I am sure it will continue to save site admins time into the future. 

Thank you.

**Comment by garethrees** [comment]
Great to hear! 🎉
