### ISSUE TITLE
Alert administrators when a body is getting requests but not replying at all

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#4935]
On WhatDoTheyKnow we've had a case of a public body apparently silently ceasing to use a FOI request email address, followed by around seven requests over the subsequent year going unanswered. 

https://www.whatdotheyknow.com/body/nhs_west_lancashire_ccg

It's a pity our users didn't report this problem to us sooner, we could have fixed it. 

We have an issue #3480 "Prompt users to alert adminstrators if they've had no response at all after say 25 working days" which might have helped. 

We tried to review this kind of thing about two years ago at #3479 one idea in the discussion which followed that was producing a public page identifying potential problems; the idea being any users could then report issues which were surfaced there to administrators.

**Comment by mdeuk** [comment]
Another public body has been in contact with WhatDoTheyKnow after being informed by a user that their request had been 'delivered' but, had, in fact, not received a reply.

https://www.whatdotheyknow.com/request/544350

While this one was caught much more quickly (by means of the user contacting the body directly), it would be useful if Alaveteli's analytics could be. used to identify bodies which don't seem to be responding to requests; or, indeed, automatically flag those which are bouncing back.

**Comment by garethrees** [comment]
In the above case we consider that _a_ mailbox previously used by an authority as delivered. It's their responsibility to route email correctly. As far as WDTK is concerned, it's been delivered and the clock starts ticking. We should be firm about this, IMO.

**Comment by MattK1234** [comment]
In a recent case on WhatDoTheyKnow, a seemingly invalid FOI email address was used for a Council for about 5 months, before a Council Officer brought the matter to our attention. Approximately 29 requests went un-responded during that time.

It's a shame none of these users alerted us to this issue, but mail logs for each request were showing successful.

The root cause of this issue was an inaccuracy in a spreadsheet provided to us from the OSIC, when this spreadsheet was uploaded to WhatDoTheyKnow the email address was changed from a working one to the invalid one.

**Comment by garethrees** [comment]
What would the threshold be? I assume what we'd want some periodic report like:

**Bodies with more than N outgoing messages where no incoming messages have been received in the last N weeks/months:**

| Body 	| Outgoing Messages 	| Incoming Messages 	|
|------	|-------------------	|-------------------	|
| Foo  	| 75                	| 0                 	|
| Bar  	| 12                	| 0                 	|
