### ISSUE TITLE
Show holding pen guesses on holding pen page

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4991]
Extracted from https://github.com/mysociety/alaveteli/issues/4584.

> Currently the system's "guess" as to where the correspondence should be directed is only available on the view raw message page. Could the guess be brought onto the holding pen's admin page; perhaps with a way to accept and redeliver all proposed guesses together (checkboxes, and a single button)?

**Comment by RichardTaylor** [comment]
This is a proposal for admining the site by taking actions in bulk on a set of requests rather than dealing with them one at a time. General ticket for this approach: "Offer options to admin the site via bulk actions" https://github.com/mysociety/alaveteli/issues/5434 

Currently on WhatDoTheyKnow we appear to be dealing with holding pen cases promptly, one at a time, as they come in. That's reliant on current human resource levels, and priorities, though.
