### ISSUE TITLE
url_title incorrectly incremented after update in Batch request

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5140]
Details in https://groups.google.com/a/mysociety.org/forum/#!topic/alaveteli-pro/O9wqdC4U6nA

**Comment by lizconlan** [comment]
Looks like it happened again here: https://groups.google.com/a/mysociety.org/d/msg/alaveteli-pro/zRERLq13b0k/87Fo8tfsBAAJ (nothing to do with the originally emailed question!)

**Comment by garethrees** [comment]
We call `update_url_title` on `InfoRequest#title=`:

```ruby
  # When name is changed, also change the url name
  def title=(title)
    write_attribute(:title, title)
    update_url_title
  end
```

I think the problem with this is that an edit through the UI will `PUT` all attributes, including `title`, which then generates the next available `url_title`.

A quick fix might be as simple as:

```diff
  # When name is changed, also change the url name
  def title=(title)
    write_attribute(:title, title)
-    update_url_title
+    update_url_title if title_changed?
  end

```

**Comment by mdeuk** [comment]
I believe I have encountered another instance of this issue on the WDTK Alaveteli instance.

Request https://www.whatdotheyknow.com/admin/requests/562084 originally had the url_title 'value_for_money_2_3';  however, at some point after setting its described_state to 'user_withdrawn' (event 4293394) this has incremented to 'value_for_money_2_5' and the original url is now generating an error.

**Comment by lizconlan** [comment]
Thanks for all the help @mdeuk!

Looks like it happens when editing the request metadata (well, when saving it) - we [call `@info_request.update_attributes(info_request_params)`](https://github.com/mysociety/alaveteli/blob/d5f659e029b440727b9341fce8429389a8edd2cb/app/controllers/admin_request_controller.rb#L54) which results in updating the title (without actually changing it), triggering `update_url_title` and recalculating the number suffix _sigh_

 A quick test on my dev box suggests that @garethrees's suggestion re `title_changed?` should fix it...

`app/models/info_request/sluggable.rb`
```diff
# When title is changed, also change the URL title
def title=(title)
  super.tap do
-    update_url_title
+    update_url_title if title_changed?
  end
end
```
