### ISSUE TITLE
Invesigate possible of converting themes to Rails engines

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#5235]
First suggested on https://github.com/mysociety/alaveteli/commit/aa9c6b15d3a021709ad5f7b3b653ca914a8c40b8 but came up again in discussion about #5234.

**Comment by garethrees** [comment]
I think the main challenge here is to ensure themes-as-engines are added to the _front_ of the load path, rather than the main app code taking precedence. This is _not_ the usual behaviour of engines, where by default they're the lowest priority and get overridden by app-specific code.

Related to https://github.com/mysociety/alaveteli/issues/1908.

**Comment by lizconlan** [comment]
> I think the main challenge here is to ensure themes-as-engines are added to the front of the load path

Might have been fixed in sprockets-rails (by loading assets via `finisher_hook`) https://github.com/rails/sprockets-rails/pull/388/files
