### ISSUE TITLE
Unexpected apparant change of request URL

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5273]
The request which was at:

https://www.whatdotheyknow.com/request/motivation_for_a_public_spaces_p

appears to be at 

https://www.whatdotheyknow.com/request/motivation_for_a_public_spaces_p_3

My reason for suspecting this is that we have support email relating to the first URL, and I can't see a request there, but there is a request which matches on the second URL. 

If there is a bug or a process which is changing request URLs we'd want to understand and address it.  Could a Pro embargo be involved? It would be surprising. 

Googling for the first URL shows it was recently available on the site as Google offers a snippet in search results. 

At the time of raising this issue I'm seeing: "Sorry, we couldn't find that page" on the first URL irrespective of if I'm logged in.

**Comment by lizconlan** [comment]
[There was a bug](https://github.com/mysociety/alaveteli/issues/5140) which wrongly caused the url to be recalculated when editing the request through the admin interface.

There's no hidden embargoed request but there is an apparently unrelated https://www.whatdotheyknow.com/request/motivation_for_a_public_spaces_p_2 which would have caused it to take ...p_3 as the next number in the sequence before the bug fix was deployed.

The fix was deployed on March 28th and that request was last edited on the 25th so I think the site is working normally at the moment. I would be happy to change the URL back if that would be helpful.

**Comment by RichardTaylor** [comment]
I hadn't been keeping up-to-date with the issues and wasn't aware of the related bug which had been fixed.

Presumably this bug wasn't always in the software. Is it possible to find out how many URLs were changed, and consider reverting them (or making both URLs work for the requests in question)?  

> I would be happy to change the URL back if that would be helpful.
Yes please. I came across this as I wanted to write to the public body about the request and it will confuse the correspondence if it is now on a new URL.

**Comment by lizconlan** [comment]
First part done - the request is now https://www.whatdotheyknow.com/request/motivation_for_a_public_spaces_p (the p_3 variant is now the one that fails)

Not sure if we can work out which were changed incorrectly though. Trying to find out.

**Comment by lizconlan** [comment]
If I understand the problem correctly, it looks as though we inadvertently introduced the bug towards the end of January

**Comment by lizconlan** [comment]
Unfortunately we don't have a way of knowing which requests were affected between the bug being introduced and the fix rolled out. Also as we can't have 2 URLs for the same request, changing it may be harmful in some cases if the new URL is already being used in preference.

We'd be happy to consider changing individual requests on a case-by-case basis though if it's clear that it's causing an access problem (the concern is accidentally causing the opposite problem by changing the address a second time).
