### ISSUE TITLE
Improve admin options for marking messages as spam

### ISSUE THREAD

**Issue by mdeuk** [mysociety/alaveteli#5352]
When tidying up a request that is receiving spam there is an option to mark the request email address as spam, meaning future emails to the address will be rejected by Alaveteli.

This is useful; however, when the option is used it doesn't work exactly as anticipated, which could lead to confusion.  In essence, the request email is only marked as spam if the admin manually copies and pastes the email address from the request admin page into /admin/spam_addresses.

This makes for less than stellar UX as it works differently to other similar options (such as the 'Destroy Message') button, and, leads to significantly more admin time being expended for a simple task.

### Steps to reproduce:

1. Visit any request and click on the relevant "Admin" link for a message (in this example, I've used [1417125](https://www.whatdotheyknow.com/admin/incoming_messages/1417125/edit) on WDTK)
2. Click on the "Spam Addresses" link<img width="322" alt="image" src="https://user-images.githubusercontent.com/249418/63174864-bc390380-c03a-11e9-9463-051b2d549473.png">
3. Note that the resulting page gives no indication that the request email has been added to the Spam Addresses list.
4. Visit the request admin page (in this instance, [304307](https://www.whatdotheyknow.com/admin/requests/304307)) and copy the request email address.
5. Re-visit /admin/spam_addresses and paste the address in. Note that the resulting prompt **now** confirms that the address has been added.
<img width="614" alt="image" src="https://user-images.githubusercontent.com/249418/63175278-98c28880-c03b-11e9-9d1a-fd49c160152a.png">

Related issues #1756, #2119

**Comment by garethrees** [comment]
Wow, it's been a long time since I [wrote this](https://github.com/mysociety/alaveteli/pull/1409).

It looks like I initially [wanted to add a "Mark as spam"](https://github.com/mysociety/alaveteli/pull/1409#issuecomment-38913533) button, but at the time that didn't happen because it ended up being too complicated to do in the allocated time. One other reason I'm not sure I considered at the time is that there can be multiple addresses in the `To` header, so we'd have to figure out a way of selecting a particular address.

However, as of 4564bd81656f400993758cb21de1908494825088 we now display the `To` addresses much more clearly:

![Screenshot 2019-08-16 at 16 22 55](https://user-images.githubusercontent.com/282788/63178576-3faa2300-c042-11e9-9a42-7913c95e176b.png)

It doesn't sound like it would be too much of a stretch to add a button that submits a given address to `AdminSpamAddressesController#create` at this point:

![Screenshot 2019-08-16 at 16 22 41](https://user-images.githubusercontent.com/282788/63178587-45076d80-c042-11e9-9e52-e7d56d47965a.png)

**Comment by MattK1234** [comment]
I might be being a bit dim here, but wouldn't we just close the request to new responses (or set it to 'authority_only')?

**Comment by garethrees** [comment]
> Presumably this is for @whatdotheyknow.com email addresses that are not requests

Yep!
