### ISSUE TITLE
Add Twitter link to public body profile

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5369]
Adding a Twitter link could help people find bodies by searching their social media username.  Some people might know their public bodies by social media username rather than by their full official name. 

Embedding a Twitter profile in a body page might give us a way to pull public body logos and descriptions from Twitter on to Alaveteli sites.  As yet Twitter don't offer a profile embedding method though https://developer.twitter.com/en/docs/twitter-for-websites/overview - it might be possible to create something like one though once we've collected usernames for bodies we could use Twitter's API to obtain bios, profile pictures, and profile header images, and display them. 

#1339 is on adding a Twitter link to a user profile

**Comment by garethrees** [comment]
Going to close this for similar reasons to https://github.com/mysociety/alaveteli/issues/1339.

Twitter is popular now, but it probably won't be around forever, which means we'll have to clean it up down the line. It also adds complexity and maintenance burden for running the site (finding Twitter ids, changing them as authorities rebrand, etc).

If we're going to do something like this I'd much rather [integrate it with wikidata](https://www.wikidata.org/wiki/Property:P8167) so that all we do is pull from a relatively trusted source.
