### ISSUE TITLE
[ERROR] request#show (NoMethodError) "undefined method `strip' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5382]
```
A NoMethodError occurred in request#show:

undefined method `strip' for nil:NilClass
app/models/incoming_message.rb:260:in `specific_from_name?'


-------------------------------
Request:
-------------------------------

* URL : https://transparencia.be/nl_BE/request/demande_de_la_composition_de
* HTTP Method: GET
* Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"demande_de_la_composition_de", "locale"=>"nl_BE"}
* Timestamp : 2019-09-29 02:03:37 +0200
* Server : owl
* Rails root : /REDACTED/alaveteli-2019-09-02T14-26-17

-------------------------------
Backtrace:
-------------------------------

app/models/incoming_message.rb:260:in `specific_from_name?'
app/views/request/_incoming_correspondence.html.erb:4:in `_app_views_request__incoming_correspondence_html_erb__3894700621597723031_70052969946440'
app/views/request/_correspondence.html.erb:4:in `_app_views_request__correspondence_html_erb___2880736604165700046_70052975628640'
app/views/request/show.html.erb:70:in `block in _app_views_request_show_html_erb___4362884285142867874_70052978526160'
app/views/request/show.html.erb:68:in `_app_views_request_show_html_erb___4362884285142867874_70052978526160'
app/controllers/request_controller.rb:133:in `block (3 levels) in show'
app/controllers/request_controller.rb:132:in `block in show'
lib/alaveteli_localization.rb:43:in `with_locale'
app/controllers/request_controller.rb:83:in `show'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
This only happens in an alternative locale:

```ruby
r = InfoRequest.find_by url_title: 'demande_de_la_composition_de'

r.incoming_messages.last.specific_from_name?
# => true

AlaveteliLocalization.with_locale('nl_BE') { r.incoming_messages.last.specific_from_name? }
# => NoMethodError: undefined method `strip' for nil:NilClass
```

**Comment by garethrees** [comment]
Lets look at what's going on here:

```ruby
# class IncomingMessage…
  def specific_from_name?
    !safe_mail_from.nil? && safe_mail_from.strip != info_request.public_body.name.strip
  end
```

We have a `safe_mail_from`:

```ruby
m = r.incoming_messages.last
m.safe_mail_from
# => "Info Controleorgaan"
```

But we only have a `PublicBody#name` for the default locale…

```ruby
m.info_request.public_body.name
# => "Organe de controle de l'information policière"

AlaveteliLocalization.with_locale('nl_BE') { m.info_request.public_body.name }
# => nil
```

…so we're trying to call `strip` on `nil`.

**Comment by garethrees** [comment]
I think this is actually a problem with underscore locales.

When we have a `PublicBody` with only the default translation, with non-underscore translations we get a fallback:

```ruby
b.translated_locales
# => [:en]

b.name(:en)
# => "Foo"

b.name(:es)
# => "Foo"
```

With underscore locales, we don't get the fallback:

```ruby
b.translated_locales
# => [:fr_BE]

b.name(:fr_BE)
# => "Organe de controle de l'information policière"

b.name(:nl_BE)
# => nil

```

**Comment by garethrees** [comment]
> I think this is actually a problem with underscore locales.

Yep. In this case, `:nl_BE` is not falling back to `:fr_BE`:

```ruby
I18n.fallbacks
# => { :fr_BE => [:fr_BE, :"fr-BE", :fr],
#      :nl_BE => [:nl_BE, :"fr-BE", :fr] }
```

**Comment by garethrees** [comment]
Manually including `:fr_BE` in the `Globalize.fallbacks` gives us what we want:

```ruby
fallbacks = {
  fr_BE: [:fr_BE, :"fr-BE", :fr],
  nl_BE: [:nl_BE, :fr_BE, :"fr-BE", :fr]
}

Globalize.fallbacks = fallbacks
# => {:fr_BE=>[:fr_BE, :"fr-BE", :fr], :nl_BE=>[:nl_BE, :fr_BE, :"fr-BE", :fr]}

b.name(:fr_BE)
# => "Organe de controle de l'information policière"
b.name(:nl_BE)
# => "Organe de controle de l'information policière"
```

**Comment by garethrees** [comment]
Also seeing these in Rwanda (likely because it has an underscore locale as the default locale). Similar cause as https://github.com/mysociety/alaveteli/issues/5890.

**Comment by gbp** [comment]
Seeing this more on Rwanda since bumping to 0.40 and/or migrating to the new infra.

**Comment by gbp** [comment]
This has an issue again since https://github.com/mysociety/alaveteli/pull/6485/commits/02ea5058a3065f439ee41482456d8b4387f6cd7f but only visible for us at mySociety since upgrading Belgium and Rwanda to 0.40. Both these sites have underscored locales (`fr_BE nl_BE` and `en_RW rw fr`)

It turns out calling [`AlaveteliLocalization.set_locales`](https://github.com/mysociety/alaveteli/pull/6485/commits/02ea5058a3065f439ee41482456d8b4387f6cd7f#diff-cf34777dfd4c2abaad286938f9f45d14e97a3fe40d532096a6f8d54aa26645d6R26-R29) in a `config.before_configuration` block doesn't persist correctly and is really needed in an `config.after_initialize` block.

Unfortunately we can't move to an `after_initialize` hook as this leads to an error when booting Rails 6.1 in development mode. This due Alaveteli not yet using the new Zeitwork autoloading feature and Rails attempts to [render a deprecation warning](https://github.com/rails/rails/blob/448856c7eb4465d0d1a5682bddd8c9fb07489d23/railties/lib/rails/application/finisher.rb#L51-L75) which happens to [includes an I18n translation](https://github.com/rails/rails/blob/6-1-stable/railties/lib/rails/application/finisher.rb#L36) so requires the default locale to be setup.
