### ISSUE TITLE
Cannot close and anonymise an account when ban text is already present

### ISSUE THREAD

**Issue by MattK1234** [mysociety/alaveteli#5489]
Today I wanted to close and anonymise a user account on WhatDoTheyKnow. When I entered the edit user page, the close and anonymise button was greyed out. I found that I had to delete the ban text and save before I could re-edit to use the button.

This probably isn't much of a problem or something that we've encountered before. It just struck me as odd.
For background, my reasoning here was the user had been banned by another admin inserting ban text. Banning doesn't prevent classifying requests (AFAIK) though. I wanted to prevent the user logging in and classifying requests as well.

**Comment by garethrees** [comment]
This is a kind-of design decision / kind-of hack.

We [disable](https://github.com/mysociety/alaveteli/blob/766dec37953288143d6673d2ca61348dd777598c/app/views/admin_user/edit.html.erb#L61) "Close and Anonymise" when the user is "suspended" – so that we don't mistakenly re-suspend users etc. Of course, adding `ban_text` also falls under this suspended category, so it gets considered when we're checking whether to enable the button.

The problem really is that we don't distinguish between some of the concepts well enough in the codebase (See https://github.com/mysociety/alaveteli/issues/3148#issuecomment-428232578).

We'll tackle improvements around this area in https://github.com/mysociety/alaveteli/issues/3148, so going to close this.
