### ISSUE TITLE
Responses being duplicated on request pages when copied to multiple requests

### ISSUE THREAD

**Issue by MattK1234** [mysociety/alaveteli#5673]
A Council sent an acknowledgement and substantive response to 614739, 614741, 614742, 614743, 614745, and 614747 (by putting each address in the to box). Each reply has been duplicated meaning that each thread has 6 acknowledgements and 6 substantive requests.

The issue doesn't appear to be with the Council's email system, it appears that the messages have been received by bittern.ukcod.org.uk as expected but are being processed slightly unusually thereafter.

**Comment by gbp** [comment]
This isn't an issue any more since [this change](https://github.com/mysociety/alaveteli/pull/7770/files#diff-839e688b765a714ce561267d4fd3448f04961292d2b0cf2b1ac81a91babe92efR245-R246). 

Issue now is that these messages are going to the holding pen, see: https://github.com/mysociety/alaveteli/issues/7879
