### ISSUE TITLE
Enable users to set prominence for their profile page

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5822]
A WhatDoTheyKnow user has written to request the ability to seek to prevent their profile page appearing in Google search results. 

It appears they want a user settable preference which would result in a  

> `<meta name="robots" content="noindex">`

tag appearing in the profile page header, or  a 

>`X-Robots-Tag: noindex`

appearing in the HTTP response header as described at

https://support.google.com/webmasters/answer/93710?hl=en

**Comment by garethrees** [comment]
Somewhat related to https://github.com/mysociety/alaveteli/issues/5496, as this is essentially "backpaging" a user account.

**Comment by garethrees** [comment]
We've had [a user](https://groups.google.com/a/mysociety.org/g/alaveteli-dev-private/c/L_BUBv0YBLA/m/DF-9XMDlAgAJ) who wanted to keep their requests public, and continue to make requests, but just not have a place which links them all together. We could look at using the prominence system for this, so e.g. a user could set:

* normal: as it is now, fully public
* backpage: sets noindex for search engines but visible & searchable to those on the site
* unlisted: not indexed, but visible with link
* requester_only: only visible to them

Would have to figure out if this affects only a portion of the content, or the entire page, and if the latter how we'd handle that.

**Comment by laurentS** [comment]
In a similar fashion, we have various users who have requested that their names be hidden on the site, including in the request pages. We have solved this temporarily by modifying the templates so that they read like `Someone made this request...` instead of `John Doe made this request...`, pretty much anywhere their names appear. But some users (I'm thinking journalists or organisation accounts) might want to have their names associated with their investigations.
We thought something like what you describe above could be a good option, where users can choose the level of privacy they want to have on their account, not just their user page.
This comes in big part from the fact that French law requires people to use their real name, not to file a request, but to appeal it (which is required more often than not).

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
