### ISSUE TITLE
Links not working on the debug page

### ISSUE THREAD

**Issue by MattK1234** [mysociety/alaveteli#5860]
Don't think it matters much... Wouldn't normally use them, only clicked them to see what they do.

Neither of these links work on the admin/debug page:

![image](https://user-images.githubusercontent.com/47503358/89827150-38cbc880-db4f-11ea-822c-5c984ff9ef97.png)

**Comment by garethrees** [comment]
Just had a bit of a look. They don't work on mySociety-hosted Alavetelis because we don't use GitHub as a primary source for deployments. They do work correctly for most other re-users though. Given we have easy access to this information for sites this affects through the console on the server I'm just going to close this.

Thanks for reporting though!
