### ISSUE TITLE
[ERROR] public_body#show (NoMethodError) "undefined method `back_url'

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#5890]
```
A NoMethodError occurred in public_body#show:

  undefined method `back_url' for #<PublicBodyController:0x00007f34b8a34690>
  app/controllers/public_body_controller.rb:36:in `block in show'
```

**Comment by garethrees** [comment]
Thanks for reporting, but useful to put the full exception notification rather than a snippet.

Here's one I just came across:

```
A NoMethodError occurred in public_body#show:

 undefined method `back_url' for #<PublicBodyController:0x00007f1ca4a69bc8>
 app/controllers/public_body_controller.rb:36:in `block in show'

-------------------------------
Request:
-------------------------------

 * URL        : https://sobanukirwa.rw/rw/body/city_of_kigali
 * HTTP Method: GET
 * Parameters : {"view"=>"all", "controller"=>"public_body", "action"=>"show", "url_name"=>"city_of_kigali", "locale"=>"rw"}
 * Timestamp  : 2020-09-22 18:42:40 +0200
   * Rails root : /data/vhost/rwanda.alaveteli.org/alaveteli-2020-09-22T15-07-36

-------------------------------
Session:
-------------------------------

 * session id: [FILTERED]
 * data: {"session_id"=>"REDACTED", "locale"=>"rw"}

-------------------------------
Backtrace:
-------------------------------

 app/controllers/public_body_controller.rb:36:in `block in show'
 lib/alaveteli_localization.rb:46:in `with_locale'
 app/controllers/public_body_controller.rb:31:in `show'
 app/controllers/application_controller.rb:116:in `record_memory'
 lib/strip_empty_sessions.rb:15:in `call'
```

In this case `https://sobanukirwa.rw/rw/body/city_of_kigali` is erroring, but `https://sobanukirwa.rw/body/city_of_kigali` is a working URL.

The body only has `en_RW` (default locale) translations:

```ruby
PublicBody::Translation.where(public_body_id: 466).pluck(:locale, :url_name)
# => [["en_RW", "city_of_kigali"]]
```

I think in this specific case I'd expect to get redirected to `https://sobanukirwa.rw/body/city_of_kigali`. This _should_ happen…

https://github.com/mysociety/alaveteli/blob/0.38.1.1/app/controllers/public_body_controller.rb#L40-L44

…but that happens after the code that tries to redirect back.

It seems like `@public_body = PublicBody.find_by_url_name_with_historic(params[:url_name])` is finding the `PublicBody` through the default locale translation, but not actually falling back to the default where the locale we're requesting doesn't have translations.

**Comment by garethrees** [comment]
Just to demonstrate the issue in the console…

```ruby
# We find the PublicBody with the default locale url_name, even though there's no RW translation.
AlaveteliLocalization.with_locale('rw') { @public_body = PublicBody.find_by_url_name_with_historic('city_of_kigali') }
# => #<PublicBody id: 466, …>

# We do have a url_name in the default locale…
@public_body.url_name
# => "city_of_kigali"

# …but url_name is nil when using the RW locale because there's no translation
AlaveteliLocalization.with_locale('rw') { @public_body.url_name }
# => nil
```

The code was [introduced](https://github.com/mysociety/alaveteli/commit/fb183ab07052293acabde9fa249f5d1952d56465) without description or tests, but it looks like its there because "no translations in this locale" is a slightly different case than "found the authority by an old `url_name`". The latter code would fail because we're relying on `url_name` existing: 

```ruby
redirect_to :url_name => @public_body.url_name
```

So, what other options do we have if this situation arises?

1. Redirect to the default locale URL
1. `404`
1. Render the default locale translation

Redirecting to the default locale URL isn't great, because that then changes the entire interface into a language the user possibly can't understand.

`404` is a technically correct thing to do – there is no public body at that URL. The `url_name` for the translation would be different.

Given we know the body exists, we could render the default locale translation of the body, but keep the selected non-default locale for the rest of the interface. This seems like the best solution, and strangely, exactly what I'm seeing in my development env!

![fallback-to-default-translation](https://user-images.githubusercontent.com/282788/93984531-d3890b00-fd7b-11ea-888a-0740862683a2.jpg)

**Comment by garethrees** [comment]
> Given we know the body exists, we could render the default locale translation of the body, but keep the selected non-default locale for the rest of the interface. This seems like the best solution, and strangely, exactly what I'm seeing in my development env!

This seems to be exactly the behaviour of WDTK

1. Default locale: https://www.whatdotheyknow.com/body/abel_smith_school_hertford
2. Non-default locale with no translation: https://www.whatdotheyknow.com/cy/body/abel_smith_school_hertford

**Comment by garethrees** [comment]
> Baffling that this behaviour is different.

Okay, so the failing URL is `https://sobanukirwa.rw/rw/body/city_of_kigali`, but `rw` is not a "valid" locale – `en_RW` is the locale and that URL works as expected https://sobanukirwa.rw/en_RW/body/city_of_kigali.

The language switcher actually sets `rw`, which is wrong. I think https://github.com/mysociety/alaveteli/pull/5891 fixes the immediate issue of an incorrect method being used, and the rest probably needs a new issue at this point.
