### ISSUE TITLE
Add snippet library to new followup page

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5911]
As per the existing workflow, once a request has been **classified** as refused we’ll take the user to **/help/unhappy** which shows them the next steps. This will either be immediately following the submission of the **classification form**, or from the **classification banner** if the request has already been classified as refused.

On the **new followup** page we’ll introduce a **template library** that allows users to better tailor their internal review based on the situation they’re faced with.

Each **template** will have some sort of title and/or short description of when to use it, and the template text itself. Clicking a template will just append the template text to the followup **message body**. This will allow the user to tweak it for their specific case, or easily delete the appended text.

**Templates** should probably be database-driven and translatable, as the specifics for each install will vary.

We’ll want some way of filtering the templates. It’s not essential that we expose filtering options to the user (that could get complicated), but they should be able to clear filters if we’ve applied them dynamically.

![Screenshot 2020-10-05 at 12 34 52](https://user-images.githubusercontent.com/282788/95074896-3036df00-0707-11eb-8cd1-163862c7d8b2.png)

**Comment by garethrees** [comment]
Note that for research purposes we'll want to record that a particular template was used. A good place for this might be in the `InfoRequestEvent#params_yaml` attribute.

**Comment by MyfanwyNixon** [comment]
I've started compiling snippets at https://docs.google.com/document/d/1IJnWbzoCGFiHYZUhG__AbP-6ReDvx8q3BCwvN_mglXk/edit.
At the moment these all refer to section 12 exemptions, and I've marked each instance on this doc https://docs.google.com/document/d/1oMuhEONlVmTJRDjonwsqi3VVp5xBDxhtkhc4sroRpU8/edit

**Comment by garethrees** [comment]
We started a bit of a conversation in Slack around automatically pre-filling these snippets based on the Q&A.

My fears with the whole auto-filling idea are:

1. we don’t have any of the existing infrastructure around showing and editing admin-editable snippets yet; that’s not an insignificant task
2. we then get into the situation of having to be more right – people won’t necessarily read all the pre-filled stuff. Not saying they always will when they click-to-add, but more chance of it, and less chance that _every_ response we send is in some way not right because of a decision _we_ made. 
3. there's the complexity in unpicking how the mechanics of the exiting hard-coded pre-filled text and admin-editable snippets interact

I don't think we've got enough remaining time to handle these in a satisfactory way, so let's park this for now. If we figure out a nice way to do it, then we can revisit if we have time.

**Comment by zarino** [comment]
Here’s a start.

If the user follows one of our links from the checklist wizard UI to the`/followups/new` page, we remove a bit of the general advice from the page (since it’s not required now we know more about the user’s intent) and we replace it with the snippet selector:

![mockup-1](https://user-images.githubusercontent.com/739624/104012905-8acd5480-51a8-11eb-964f-fff111e33426.png)

The list of snippets is pre-filtered based on your answers to the wizard, but if you want, you can browse the full list of snippets, or snippets grouped by sections of the FOI legislation, using the filter:

![mockup-2](https://user-images.githubusercontent.com/739624/104012984-ac2e4080-51a8-11eb-8062-00967f7bfe19.png)

If the user reaches the `/followups/new` page _without_ coming via the wizard (ie: we don’t know what snippets to suggest to them) we could maybe hide the snippet browser by default and instead add a line like "Challenging a refusal? <u>Browse our library of helpful snippets.</u>" – clicking the link would reveal the snippet browser, which would work the same as above, except without the "my previous answers" filtering option (because the user hasn’t provided any answers).

Thoughts, @garethrees @MyfanwyNixon ?

**Comment by garethrees** [comment]
**Love** it! Really fantastic! 👏  Particularly like the filter; that's really nice.

Couple of thoughts:

1. How does a user see the full snippet text? Looks like it might be longer than the 2 lines we show here. Should there be a preview step, or a details unfold, or do we just add it to the input and let them delete it if they don't like it?
2. How are we going to handle 3+ snippets? I don't know how many snippets will be relevant for any given refusal, but I imagine more than a handful. Certainly "any section" will be a loooong list. Will there be enough space above the correspondence input to navigate them in a nice way?

**Comment by zarino** [comment]
On seeing the full snippet text – two solutions spring to mind, but I’m not sure which will feel right to a regular user:

1. A "(more)" link or something, after each snippet, to expand the remainder of the snippet, inline.
2. No way to preview the full snippet, you just have to insert it.

I went with option 2 for the mockups above, but I’m not set either on it. Seems logical that people will want to preview what they’re about to "insert", and it isn’t obvious how to do that, if inserting is the only action you can see.

On numbers of snippets – I was thinking the box would have a set maximum height, and be `overflow: auto` so a scrollbar appears if there are more snippets than will fit.

If there are only a few snippets, (or maybe just when the filter is set to "my previous answers", since we can be pretty sure that _all_ of those snippets will be relevant) I was wondering whether we disable the scrolling, so all the snippets are visible. Feels like a nice-to-have. Fairly easy to implement.

Either way, my instinct is we’d avoid the scrolling on narrow devices (as a proxy for touchscreen devices, where things that scroll _within_ the page are always really awkward) and maybe just have `max-height: none; overflow: visible;` for them, with the filters `position: sticky` so they remain visible even as you scroll down. You’ll still need to scroll a long way if you select a filter option that results in lots of snippets, but at least it’ll feel more natural than scrolling an element within a scrollable page. (Not convinced on this! Should probably check how many people write FOI requests on a mobile device, so we can work out how much time to spend on getting this right.)

**Comment by zarino** [comment]
Actually, I can answer my own question at the end there – of sessions on whatdotheyknow.com during the last 3 months of 2020, where the session included a visit to the `/followups/new` page (making for a total of 12677 sessions), 77% were made via a desktop browser, 19% via a mobile device, and 4% via a tablet.

**Comment by garethrees** [comment]
> 19% via a mobile device, and 4% via a tablet

Not insignificant then, which is kinda 🤯  to me with my iPhone SE.

> two solutions spring to mind

Another option would be for insert to show a modal with the full snippet text, which itself has an "insert" button. Obviously a little slower, but still quicker than writing the text yourself, and maybe less hassle than immediately deciding you didn't want that snippet and trying to delete it from the text area.

One thing this would allow is for the snippet to be loaded into an intermediary text area where the user could tweak that particular phrase, and _then_ insert it into the main correspondence text area. IDK if that just seems pointless though, and I don't have a really strong opinion on any of this right now.

> If there are only a few snippets… I was wondering whether we disable the scrolling, so all the snippets are visible. Feels like a nice-to-have. Fairly easy to implement.

Makes sense to me and avoiding scrollbars is always nice.

> so they remain visible even as you scroll down

I can't imagine this leaving much text editing space on a mobile – perhaps I just need to get with the times and buy a phablet though…

**Comment by zarino** [comment]
> > so they remain visible even as you scroll down
> 
> I can't imagine this leaving much text editing space on a mobile – perhaps I just need to get with the times and buy a phablet though…

Sorry, I mean the _filter_ at the top of the list stays visible, _within_ the confines of the list, stuck to the top of the screen. If you scroll past the list, to the `textarea`, then the filter moves off screen with the list. If you get what I mean. (It’s CSS `position: sticky`).

**Comment by zarino** [comment]
Trying out a few options, a "(read more)" link at the end of each snippet feels like the most intuitive option.

![Screenshot 2021-01-08 at 14 07 18](https://user-images.githubusercontent.com/739624/104024323-dbe64400-51ba-11eb-82c0-67cdd18cbbec.png)

**Comment by garethrees** [comment]
Think the next steps on this are:

* Add the above mockup into the template itself with some stubbed data
* Add the MVC backend
  * `OutgoingMessage::Snippets`. Why snippets?
    * We already have OutgoingMessage::Template
     * We might want to later provide a `Template` based on a collection of snippets
  * Should be translatable
  * Should be taggable
* Make the "insert" button add the snippet content to the correspondence textarea

**Comment by gbp** [comment]
Thinking about how to link the wizard to the new followup page. If the user lands on the wizard directly then where is the "Help me send a reply" button going to link - we won't know which request is to follow up on?

**Comment by garethrees** [comment]
> If the user lands on the wizard directly then where is the "Help me send a reply" button going to link - we won't know which request is to follow up on?

Good question, but not one for this issue right now.  Extracted to https://github.com/mysociety/alaveteli/issues/6063.

**Comment by gbp** [comment]
I put my current thinking in the commit message here: https://github.com/mysociety/alaveteli/commit/e001060a4b5de0076c14a375586da5f8dfbd74b3

**Comment by garethrees** [comment]
I should have written this up after @gbp and I spoke about this last Thursday. The main points were.

**Snippets as YAML**

* We already have the YAML "infrastructure", and it makes change a little easier
* We could parse out the IDs of each action and use those to map to snippets; Pairing `response_template` with tags requires admins to know about configuration files.
* "Free" translations through transifex
* Unclear how to map this data structure to the UI filter; How do we get "all snippets for section N"?

**Snippets in the database**

* Allows snippets to be useful even if the Q&A isn't configured
* Snippets are more volatile than the Q&A data; admins will want to tweak wording as they get more experience with what works. The Q&A is more stable because the law doesn't change as often.
* Admin-editable means less programmer burden for changes; The Q&A is difficult to edit irrespective of the UI, so adding it to the admin interface wouldn't be a big benefit. The snippets are easily understood by others though, so we don't want to require programmer intervention every wording change.
* Clear how to map this data structure to the UI filter; How do we get "all snippets for section N"? `Snippet.with_tag(`section_12`)`

We're working on the backend for snippets in the database to be able to compare approaches, but I'm leaning heavily towards the original suggestion of making them DB-backed.

**Comment by zarino** [comment]
FWIW my instinct is that storing the snippets in the database (so regular site admins / volunteers can more easily edit them) is the right answer.

**Comment by gbp** [comment]
I've push my latest to https://github.com/mysociety/alaveteli/compare/jrct/snippet-library-gbp this replaces the single commit on @zarino's `jrct/snippet-library` branch.

It's is now using a model backend to power the snippets, it stores the result of the wizard as an `InfoRequestEvent` which is then loaded on the followup up form (see the `data-filter` attributes)  in order to do the snippet filtering.

Todo:
- [ ] tests
- [ ] filtering of the snippets
- [ ] inserting into the textarea
- [ ] recording which snippets are used - in InfoRequestEvent?

**Comment by MyfanwyNixon** [comment]
I've finished writing and proofing the snippet texts https://docs.google.com/document/d/1IJnWbzoCGFiHYZUhG__AbP-6ReDvx8q3BCwvN_mglXk/edit

**Comment by garethrees** [comment]
Resolved by https://github.com/mysociety/alaveteli/pull/6099
