### ISSUE TITLE
Option to send reply to the main FOI contact address for {{public_body}} not offered

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#5942]
A WhatDoTheyKnow requester was not given the option of choosing to send a reply to the main FOI email address for a public body. 

In the specific case a ticket was created to list the "no-reply" address for special treatment:
https://github.com/mysociety/whatdotheyknow-theme/issues/724

Shouldn't users always get the option to "send reply to the main FOI contact address for {{public_body}}" ?

I think this may be a bug rather than a feature request but I'm not sure. 

<img width="729" alt="Screenshot 2020-10-28 at 12 21 19" src="https://user-images.githubusercontent.com/547695/97435648-9d115380-1918-11eb-9b6d-76993f52f78e.png">

**Comment by mdeuk** [comment]
> A WhatDoTheyKnow requester was not given the option of choosing to send a reply to the main FOI email address for a public body.

> 
> Shouldn't users always get the option to "send reply to the main FOI contact address for {{public_body}}" ?
> 

I think I can explain this one. I've looked at message [1665914](https://www.whatdotheyknow.com/admin/incoming_messages/1665914/edit) and it appears that the "no-reply" address being used here is the sender/envelope address, however, the "From" and "Reply-To" headers have the public body's main email address within (even though the name implies otherwise!).

We've seen a similar issue in the past with the DWP and MOD - the data presented in the messages is slightly misleading, giving the suggestion that a user would be unable to reply to the message, which is of course not the case.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/249418/97436560-1cebed80-191a-11eb-97a2-c999823edca2.png">

I'd surmise that Alaveteli is not offering the option to use the "main" address because this address matches - however, perhaps we could do a better job of presenting the information so as to avoid confusion?

Should we perhaps sanitise the output here so that we aren't rendering an email address in the plain text? We already do this for bodies where there is no sender name specified (for example, request [692070](https://www.whatdotheyknow.com/request/pubsbarsrestaurantscoronavirus_f#incoming-1666107)), so it might be of benefit if we consider doing something similar here.

**Comment by RichardTaylor** [comment]
I don't think this is a bug with the system then, it's just very unusual behaviour on the part of the public body.

**Comment by garethrees** [comment]
Just linking this to https://github.com/mysociety/alaveteli/issues/4354 as a bit of a weird edge case to consider.
