### ISSUE TITLE
No script for migrating public body categories -- script/migrate-public-body-categories

### ISSUE THREAD

**Issue by ninoarsov** [mysociety/alaveteli#5975]
Hello,

In the latest version the script `script/migrate-public-body-categories ` is not available. Is there another way to migrate (import) public bodies and their categories?

We would also like to have 3 levels of categories. This means beside the headers and categories, we also need a subcategory. Is this possible in the current version of Alaveteli?

**Comment by garethrees** [comment]
> In the latest version the script `script/migrate-public-body-categories` is not available. Is there another way to migrate (import) public bodies and their categories?

Looks like we cleaned that up in b61e6b27c and e6511423e9334973ecd8d808c3b73c1b4e312935 back in 2015.

What version of Alaveteli are you running? If you're on an old version, you should upgrade one version at a time, where these migration scripts will still be available. It is not recommended to jump several major versions at once.

> We would also like to have 3 levels of categories. This means beside the headers and categories, we also need a subcategory. Is this possible in the current version of Alaveteli?

We don't currently or plan to support this I'm afraid. I'd heed Edward Tufte's advice on [levels of headings](https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0000hB):

> It is also notable that the Feynman lectures (3 volumes) write about all of physics in 1800 pages, using only 2 levels of hierarchical headings: chapters and A-level heads in the text. It also uses the methodology of sentences which then cumulate sequentially into paragraphs, rather than the grunts of bullet points. Undergraduate Caltech physics is very complicated material, but it didn't require an elaborate hierarchy to organize. A useful decision rule in thinking and showing is "What would Feynman do?"

Bodies can appear in more than one category though, so that should give you enough flexibility of organisation. If it doesn't, please do describe what you're aiming to do in a bit more detail and we can see if we can figure something out.
