### ISSUE TITLE
Change translation platform

### ISSUE THREAD

**Issue by comradekingu** [mysociety/alaveteli#5978]
Transifex leaks user info left and right, (I'd link to the various documents here, but they load a lot of spying scripts) and makes it downright impossible to request the bulk of this information.
How it may be transferred is intentionally left vague in their terms and conditions, cookie policy and other documents.
Not that this problem should exist in the first place.

Furthermore it is a mess of a platform, and one that requires projects to have no source of income to be awarded the service of using its translators as commissioned workers to build up a stringbase, and extracting info about them.

[Handlingar.se](https://gitlab.com/handlingar/handlingar/-/issues/340#note_438521645) wants to move to Weblate, but needs your support.

Alaveteli can change its policy, set up a instance of its own, or use Hosted Weblate.

**Comment by garethrees** [comment]
We're always interested in alternatives to current third-party services, but I don't think we'll have the resources to migrate away from Transifex any time soon.

We certainly wouldn't want to host our own Weblate instance, and looking at their [libre plan](https://weblate.org/en/features/), it only supports 1 "project". We use several Transifex projects for theme translations.

I guess it might be possible to reconfigure Alaveteli in such a way that it can use translations from several sources – Transifex, Weblate, whatever – but that's not something we have plans to consider.

I'm going to close this issue since at this point, it's not something we'll be able to take forward, but I do think it's worth posing this question to the [developer mailing list](https://groups.google.com/forum/#!forum/alaveteli-dev) to see if there's lots of community support for the idea.

**Comment by comradekingu** [comment]
@garethrees It supports as many projects you want, but it needs to be in the same GitHub org. Or you could register multiple ones I suppose.
You can't re-license someone elses work by sending it to Transifex that way. Another reason why Transifex sucks.
I can help set it up if you want. Not super good at it, but I have set up a few projects.
