### ISSUE TITLE
Make domain comparison that allows responses when a request is set to authority_only case insensitive

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6030]
This follows an issue which arose while running WhatDoTheyKnow. 

I don't know if the current comparison is case sensitive or not. 

This is a rare problem as usually email addresses are lower case.

**Comment by garethrees** [comment]
As far as I can tell we do test in a case-insensitive way.

We don't explicitly convert case [at the point of comparison](https://github.com/mysociety/alaveteli/blob/6ec08fb8475cc27df3292c6df4556ceab0f28abf/app/models/info_request/response_gatekeeper/authority_only.rb#L24), but tests still pass with this change:

```diff
diff --git a/spec/models/info_request/response_gatekeeper/authority_only_spec.rb b/spec/models/info_request/response_gatekeeper/authority_only_spec.rb
index 23ba866c1..e4ea066ea 100644
--- a/spec/models/info_request/response_gatekeeper/authority_only_spec.rb
+++ b/spec/models/info_request/response_gatekeeper/authority_only_spec.rb
@@ -82,7 +82,7 @@

       it 'allows the email' do
         raw = <<-EOF.strip_heredoc
-        From: authority@example.com
+        From: authority@EXAMPLE.COM
         To: request-123@example.com
         Subject: Basic Email
         Hello, World
```

The [public body that gets set up for the test](https://github.com/mysociety/alaveteli/blob/6ec08fb8475cc27df3292c6df4556ceab0f28abf/spec/models/info_request/response_gatekeeper/authority_only_spec.rb#L91) (via the `:info_request` factory) will have a [default `request_email` of `request@example.com`](https://github.com/mysociety/alaveteli/blob/6ec08fb8475cc27df3292c6df4556ceab0f28abf/spec/factories/public_bodies.rb#L28).

Diving into the test execution with pry, when we [extract the sender domain](https://github.com/mysociety/alaveteli/blob/6ec08fb8475cc27df3292c6df4556ceab0f28abf/app/models/info_request/response_gatekeeper/authority_only.rb#L18) it gets downcased:

```ruby
sender_domain = PublicBody.extract_domain_from_email(sender_email)
# => "example.com"
```

The method used to [extract the domains allowed to send to the request](https://github.com/mysociety/alaveteli/blob/6ec08fb8475cc27df3292c6df4556ceab0f28abf/app/models/info_request/response_gatekeeper/authority_only.rb#L23) explicitly [downcases the return value](https://github.com/mysociety/alaveteli/blob/6ec08fb8475cc27df3292c6df4556ceab0f28abf/app/models/public_body.rb#L649).

Whatever the problem was, I don't think this is the cause.

Going to close, but feel free to add any further info and we'll reopen if we think we can figure out what's happening.
