### ISSUE TITLE
WDTK user reports draft being lost after logging in

### ISSUE THREAD

**Issue by MattK1234** [mysociety/alaveteli#6106]
WDTK support mail - full message will be forwarded to dev@ with this ticket ref.

- User accessed WDTK and was already logged in
- Used drop down menu next to name to locate requests
- Drafted a new request then went to submit it before being told to log in again
- After login request was lost.

The user has confirmed their email address and appears to be experienced with the process of making requests.

The user is understandably frustrated at having lost the request they drafted.

I'll ask the user what browser and OS they're using for starters.

**Comment by garethrees** [comment]
Linking to [full report](https://groups.google.com/a/mysociety.org/g/alaveteli-dev-private/c/XcYxVKxpjCE/m/zoEy0I0SAAAJ).

Sometimes I "appear" to be logged in because of caches (in that the user menu still appears and the links work), but then on a new page reload (after following a link, say) I'm signed out. That might explain the first 3 bullet points, but I'm surprised that the request was then lost. That seems like it should be handled through the existing workflow.

**Comment by garethrees** [comment]
Going to close this as we won't have the logs for this now, and we haven't had widespread reports of this.

Proposed an improvement based on this though https://github.com/mysociety/alaveteli/issues/6536.
