### ISSUE TITLE
Incorporate a pseudonym generator into the service

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6174]
This could be based on popular names in the country/region a site serves. 

This feature could help those who find it difficult to come up with pseudonyms that don't look like obvious pseudonyms.

**Comment by garethrees** [comment]
I think this is creeping quite far outside the scope of Alaveteli. Making this work globally would be a challenge, and I'm sure there are plenty of "popular baby names" websites that cater for country-specific names.

I'm going to close this for now, but link to https://github.com/mysociety/alaveteli/issues/285#issuecomment-452820327 since that capability may open up a route to doing this in a less arduous way.

**Comment by RichardTaylor** [comment]
Linking to #1776 "Allow requestors to opt not to have their name shown publicly". 

Both issues relate to seeking to make the services accessible / attractive / easy to use for more potential users.
