### ISSUE TITLE
Pro referral coupons can't work unless STRIPE_NAMESPACE is all capitals

### ISSUE THREAD

**Issue by mlandauer** [mysociety/alaveteli#6186]
I know a weird and obscure bug.

In the example `general.yml`:
```
# Examples:
#
# STRIPE_NAMESPACE: 'alaveteli'
```

the example namespace is all lower-case. If you then create a referral coupon with the ID `alaveteli-REFERRAL` that then displays on the subscription page the referral code "REFERRAL" to the user. The problem comes when another user tries then to use that referral code. Alaveteli will actually look for a referral coupon with the ID `ALAVETELI-REFERRAL` which doesn't exist so the referral coupon doesn't work for the new user signing up.

I'm not sure, because I haven't looked, where this conversion is taking place. However, I expect you can work around this by only using a STRIPE_NAMESPACE which is all capitals. By a small comment in the code I'm guessing that WhatDoYouKnow uses "WDTK" for the namespace, so is that why this bug hasn't surfaced before?

**Comment by garethrees** [comment]
> I'm guessing that WhatDoYouKnow uses "WDTK" for the namespace

Indeed!

We do indeed [upcase the namespace](https://github.com/mysociety/alaveteli/commit/15864f2a24e82dd583dd1a521de451d5dc267d96#diff-6f01fba9626ca6de5e3f08d2a14fc533d43aa2d5337d879027bfc3d1c45b95aeR162) because, at least at the time of writing the feature, Stripe coupons need to be all uppercase.

We could tweak the case in [a more global place](https://github.com/mysociety/alaveteli/blob/64c13e6690a5541c1cd93943fa490543bd029413/app/controllers/concerns/alaveteli_pro/stripe_namespace.rb), but that wouldn't avoid this issue, where you're expecting a lowercase namespace in the Stripe dashboard and we're automatically upcasing it.

I think we should just add a note to `config/general.yml-example`.
