### ISSUE TITLE
"only accessible to WhatDoTheyKnow Pro users" message appears in places it shouldn't

### ISSUE THREAD

**Issue by abibroom** [mysociety/alaveteli#6214]
e.g. the homepage, for me:

![Screenshot from 2021-04-18 10-48-02](https://user-images.githubusercontent.com/560001/115141350-a8c21500-a033-11eb-886d-9377b283a75b.png)

I'm logged in as a Pro user so presumably shouldn't see that banner at all, anywhere, ever.

**Comment by garethrees** [comment]
> it might be relevant that I am not an ordinary Pro user - this account has `admin` and `pro_admin` roles.

Yeah, I imagine it's this (though, you incorrectly appear to have the `pro` label in the logged-in user menu dropdown).

What was the URL you were on? I wonder if after login you've been redirected to the "pro" homepage (the dashboard) but because you're only a `pro_admin` you don't have permissions for the page and then get redirected back to the homepage.

**Comment by abimysoc** [comment]
Unfortunately I can't retrieve the exact path that led me there. I do remember, though, that I didn't log in as part of Sunday's WDTK-browse, I was already logged in from previous visits.

**Comment by garethrees** [comment]
Difficult to reproduce from what we know and haven't had any/many reports of this. Might be something that only affects admins too, which we wouldn't be as bothered about.
