### ISSUE TITLE
Add better intro to /help/unhappy

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6236]
From initial [volunteer feedback](https://groups.google.com/a/mysociety.org/g/alaveteli-dev-private/c/fSmxSKssIMQ/m/64k6aG9BAgAJ).

Agreed – we just dumped the refusal advice rendering at the top of the page initially, but we should better incorporate it – even just a heading and short sentence about what it is.

**Comment by wrightmartin** [comment]
Having a bit of a think and scratch around about this one

### 1

# What you can do now

If you're unhappy about the response you've received from <authority> there may be more you can do. Answer some questions about what they said in their response and we'll give you the best next steps


### 2

# Unhappy with your response?

Depending on what <authority> said in their response there may be more you can do. Determine your next steps by answering the following questions


### 3

# Next steps

# If you're unhappy with how <authority> has handled your request there's always more you can do, answer the following questions and we'll give you some options for your next steps

@MyfanwyNixon might be better to take a run at this one

**Comment by MyfanwyNixon** [comment]
I think maybe a combination of all of these. Couple of things that spring to mind:
- 'Unhappy' feels a bit emotional and users might think 'I'm not exactly _unhappy_...'. In fact let's take their feelings out of it altogether: if there's an opportunity to request a review they should take it.
- We could put the stress on the fact that the information hasn't been released, rather than on the authority potentially having handled the request wrongly (which may or may not be true)

### What you can do now

A refusal from an authority doesn't always have to be the end of your FOI request. Answer the following questions and we'll give you some options for your next steps.

**Comment by garethrees** [comment]
Note that I've made a PR since authoring this issue (https://github.com/mysociety/whatdotheyknow-theme/pull/817) which may resolve many parts of it. Very happy to incorporate improvements though!
