### ISSUE TITLE
Discourage one-word usernames

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6284]
Users may actually only have one name - any warning should be considerate of this. 

It is good to advise users of the consequences of using a pseudonym. This warning / pointer to advice is already pretty strong but could be improved. 

This is a suggestion from a FOI officer.

**Comment by MattK1234** [comment]
Linked to https://github.com/mysociety/whatdotheyknow-theme/issues/15

**Comment by garethrees** [comment]
Could use the same mechanism as https://github.com/mysociety/alaveteli/issues/6828#issuecomment-1057239338.

**Comment by RichardTaylor** [comment]
+2 from today's support mail. 

* User wanting us to change their username which was just a first name after they've signed up to make their first handful of requests and found they were being asked to give their full name. 
* FOI officer urging us not to allow single names, as their organisation's policy is to request a full name, which they say draws out the process unnecessarily. 

We do want to allow those who just have one name to use the service, but perhaps this is such an unusual case and it wouldn't be unreasonable to target the advice/process at those who unwittingly think a firstname only (or something else which doesn't look like a real name) will be fine. 

I think we need a strong, but skippable, warning.

**Comment by garethrees** [comment]
![Screenshot 2023-06-02 at 13 43 45](https://github.com/mysociety/alaveteli/assets/282788/15d0552a-0c24-4109-a349-ec56d7c72b3b)

Vimeo makes this nice and clear ("First and last name")

**Comment by HelenWDTK** [comment]
+1 An FOI officer has got in touch saying that they have to deal with lots of invalid names, and has suggested that we try to technically enforce multi-name usernames somehow.

**Comment by garethrees** [comment]
https://stackoverflow.com/questions/24628628/efficient-way-to-report-record-validation-warnings-as-well-as-errors has some nice rails-based suggestions. It looks a little more geared to "editing" rather than "creating".

When editing, you could just show the warnings after save to encourage the user to edit and save again.

In this context, on creating we'd need to prevent a save the first time to show the warnings, but then allow the next form submission to save even if there are fields which would cause a warning.

Alternatively, we could keep preventing save when there are warnings so users don't only have one chance to get it right. We could then have a checkbox that says "ignore warnings" or something if warnings are present that the user can click when they feel happy that they're submitting good data.

**Comment by WilliamWDTK** [comment]
A WDTK user has got in touch to complain that our system does not force users to submit a request with a valid name.

**Comment by confirmordeny** [comment]
When we ask for the person's name (real name or pseudonym) we could collect title, first name and last name separately (allowing for mononyms). If user is or wants to be called "John Smith" we could then offer a number of 'display as' options e.g. "Mr Smith, "J. Smith", "Mr J Smith", "John Smith". 

We could default to and recommend names of the form "Mr Smith". This would reduce the amount of personal data that is publicly displayed on the site and that appears in outgoing messages and therefore the amount in incoming messages.

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
