### ISSUE TITLE
Three minor tweaks related to the way occurances of the request_address in responses are handelled 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6634]
1. The replacement of an email address with 

> [<body name> request email]

appears to be based on a case sensitive match. Make it case insensitive so more occurrences are caught. 

2. Link the 

> [<body name> request email]

text to the relevant `https://www.whatdotheyknow.com/body/body_name/view_email` page so users can view it.

3. Add text to the `https://www.whatdotheyknow.com/body/body_name/view_email` advising users to keep correspondence on the site so far as they can, both so there's a full record of the correspondence in public, and to avoid giving the public body the opportunity to respond privately. 

Ticket logged following a user support thread asking for a removed email address to be revealed. The case involved an email address with different capitalisation to the request_address.

**Comment by garethrees** [comment]
Extracted these to two separate issues since the first is a much quicker change than the others (not that 2 & 3 are _that_ complicated, but would need a bit more thinking about the text and ensuring the interpolation of the correct body works)

- https://github.com/mysociety/alaveteli/issues/6636
- https://github.com/mysociety/alaveteli/issues/6637
