### ISSUE TITLE
Commit tweaks to storage.rb

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#6717]
We've currently got this diff in production. Let's check in these lines so that a deploy doesn't obliterate them.

```diff
diff --git a/lib/tasks/storage/storage.rb b/lib/tasks/storage/storage.rb
index c91fa45d6..62926f56d 100644
--- a/lib/tasks/storage/storage.rb
+++ b/lib/tasks/storage/storage.rb
@@ -26,6 +26,7 @@ class Storage

       erase_line
       print "#{prefix}: Migrated #{index + 1}/#{count}"
+    rescue Errno::ENOENT
     end

     erase_line
@@ -93,7 +94,7 @@ class Storage
   def unattached_files
     @klass.left_joins(:"#{@association}_attachment").where(
       active_storage_attachments: { id: nil }
-    )
+    ).joins(:incoming_message)
   end

   def blobs
```

**Comment by gbp** [comment]
Background: these changes were required for the `bin/rails storage:migrate` task to run without erroring (still running hopefully there won't be any other issues).

There were two issues:
1. Missing raw email files on disk. Only seen once but this looks to be due to how we use to deal with spam. Added the `rescue` above to skip these for now. We should output a list of missing files for investigation.
2. Some raw emails (which is all we're migrating right now) have no assoication incoming request. Not sure why and needs invesigation. Possible due to holding pen messages that have been moved to a new request. The added `joins` while fine for raw emails might not work for other models with attached `ActiveStorage` files.
