### ISSUE TITLE
Bug when bulk hiding comments

### ISSUE THREAD

**Issue by sallytay** [mysociety/alaveteli#6730]
Note from @mdeuk 

When trying to hide comments on request 264053, after selecting either one or several comments, I'm getting a 404 error.

Steps to reproduce:
Select checkbox next to a comment - 93393 for example
Click "Hide selected"
Note the POST to https://www.whatdotheyknow.com/admin/users/modify_comment_visibility
Note the resulting 404 error.
Hiding comments manually, e.g. via the options in the "edit annotation" screen, works as expected - but this prevents a "select all and done" approach, which can otherwise be done quite easily.

I've tried this on both Firefox and Edge (ha) on Windows - I can also test on a Mac if that'd be helpful.

**Comment by garethrees** [comment]
I make [some changes](https://github.com/mysociety/alaveteli/pull/6670) around this feature recently.  

Wonder if the 404 is being caused by not being able to look up the comment [now it’s scoped](https://github.com/mysociety/alaveteli/pull/6670/commits/2ccd7c0ab203a251d9458347e8cc01ad2f5b7f80) to `@admin_user`.

I think what’s happening here is that the commit works when bulk-modifying annotations on the user page, but not on the request page, since there’s no user to look up.

**Comment by garethrees** [comment]
Should be able to just `git revert 2ccd7c0ab203a251d9458347e8cc01ad2f5b7f80` to fix this.

**Comment by mdeuk** [comment]
> I make [some changes](https://github.com/mysociety/alaveteli/pull/6670) around this feature recently.
> 
> Wonder if the 404 is being caused by not being able to look up the comment [now it’s scoped](https://github.com/mysociety/alaveteli/pull/6670/commits/2ccd7c0ab203a251d9458347e8cc01ad2f5b7f80) to `@admin_user`.
> 
> I think what’s happening here is that the commit works when bulk-modifying annotations on the user page, but not on the request page, since there’s no user to look up.

I'm afraid it doesn't seem to work as expected from a user admin page either 😢 .

From user 2779, I've tried hiding comments 101220 and 101193 - the steps to reproduce are broadly similar to those on @sallytay's message.

` POST https://www.whatdotheyknow.com/admin/users/modify_comment_visibility
[HTTP/2 404 Not Found 147ms]
utf8	"✓"
authenticity_token	"[REDACTED]"
comment_ids[]	[…]
0	"101220"
1	"101193"
hide_selected	"Hide+selected" `
