### ISSUE TITLE
Add prominence reason to entire request

### ISSUE THREAD

**Issue by sallytay** [mysociety/alaveteli#6746]
When hiding specific messages you can manually add a free text prominence reason. 

It would be useful if this was also available when hiding whole requests, alongside the pre set prominence reason that we have now. So that you only need to add 'free text'  should you want to.

Sally

**Comment by RichardTaylor** [comment]
Consider if we want the URL to be "active" at all when we've hidden a whole request.  URLs can themselves be problematic. 

A current work around here would be hiding all the individual messages on the request [with prominence reasons or annotations]. 

I can see this feature may be useful for transparency reporting, and running the service transparently.

See also:  "Data collection improvements to enable better transparency reporting"  https://github.com/mysociety/whatdotheyknow-theme/issues/938

**Comment by garethrees** [comment]
> Consider if we want the URL to be "active" at all when we've hidden a whole request

I think we should extract this out to a different issue if we think it's important, since implementing this is quite a different concern and they don't have to be done at the same time.

**Comment by RichardTaylor** [comment]
I think this issue needs clarifying. 

Does it refer to a public prominence reason?
Is the aim only, or mainly, transparency for those visiting a link to a hidden request, or is the aim better statistical record keeping to enable transparency reporting?
If the aim is better statistics/reporting we probably want more finely grained classifications / reasons for hiding. 

The prominence reason given when an individual message on a thread is hidden is generally public (it is public unless the whole request is hidden, requester_only, or embargoed).

The pre-set reasons we have for making a whole request hidden or requester_only eg. "vexatious" or "not FOI" are actually "classifications" rather than prominence reasons. We don't currently show these reasons to those who are not admins or the requester. We show 

>Request has been removed
>The request you have tried to view has been removed. There are various reasons why we might have done this, sorry we can't be more specific here. 

and that page is served with a header:

> 403 Forbidden

Is the proposal here to expand that with a prominence reason / classification such as "vexatious" / "not a FOI request", and  a free text statement too?  We wouldn't show the free text but not the classifications would we? If a request has been hidden as vexatious we don't currently say the reason it was hidden is vexatious on the "request has been removed" page. 

(The system also knows if a request has been hidden as personal correspondence, or a subject access request - more specific categories of "not a FOI request"). 

Improvements in this area would improve transparency, and and perhaps transparency reporting too. 

>Consider if we want the URL to be "active" at all when we've hidden a whole request
>> I think we should extract this out to a different issue 

That URLs of hidden/requester_only requests are "active" is something to bear in mind if we are to put more content on those pages. It's also important admins know that hiding a request doesn't stop the URL "existing" and either changing the title/subject or deleting the request is needed to fully achieve that. 

I suspect the URL issue isn't significant given the 403 header probably stops them ending up in search engine results. 

An error page with a 403 status is quite different to a request page with all the messages hidden on it.

**Comment by garethrees** [comment]
Requires https://github.com/mysociety/alaveteli/issues/6790.

**Comment by garethrees** [comment]
## Current situation

Currently we don't have an `InfoRequest#prominence_reason` attribute.

When an `InfoRequest` is made `requester_only` or `hidden` we just show a generic message ("There are various reasons why we might have done this, sorry we can't be more specific here."):

`requester_only`:
<img width="1272" alt="Screenshot 2022-05-20 at 16 07 19" src="https://user-images.githubusercontent.com/282788/169558849-f598a67c-1a85-49df-b2fe-8764b39b7e56.png">

`hidden`:
<img width="1272" alt="Screenshot 2022-05-20 at 16 07 37" src="https://user-images.githubusercontent.com/282788/169558877-01647983-82a3-4dfc-9ed9-e3000eda1b8c.png">

## Proposal

This issue proposes adding a `InfoRequest#prominence_reason` attribute, and displaying it instead of the generic message:

`requester_only`:

<img width="1272" alt="Screenshot 2022-05-20 at 16 11 00" src="https://user-images.githubusercontent.com/282788/169559260-39ce3947-1f5f-4ad9-813d-53136364095a.png">

`hidden`:

<img width="1272" alt="Screenshot 2022-05-20 at 16 09 55" src="https://user-images.githubusercontent.com/282788/169559281-b3941974-1a17-4dda-9179-b92ee2fd295f.png">

`InfoRequest#prominence_reason` should be editable through `/admin/requests/:id/edit` as a `textarea`.

`InfoRequest#prominence_reason` should be optional, and `nil` by default.

When `InfoRequest#prominence_reason` is updated, it should log the prominence reason on the event:  https://github.com/mysociety/alaveteli/issues/6790

## Out of Scope / Not Doing

There's no intention to change any of the URL routing.

There's no intention to change the HTTP response code.

There's no intention to show the classification on the page.

**Comment by RichardTaylor** [comment]
I think we need to give more thought to when and how we'd use this feature. 

If we were to add a prominence reason of eg. "removed as not a FOI request" every time we remove a thread for that reason then we should integrate that with the not_foi classification, similarly with vexatious, and ideally also with personal correspondence (which we handle slightly differently).

I suspect we would use it, but I'm not sure when, or if it would be better than hiding all the messages and adding a special admin annotation (#34).

**Comment by RichardTaylor** [comment]
I had a case today where I could have used this, or to have a similar, but perhaps better and more transparent effect:

https://github.com/mysociety/alaveteli/issues/1954

**Comment by garethrees** [comment]
At present we have 10k+ requests where we're giving no explanation as to why the request is not visible to the average viewer.

```rb
InfoRequest.where(prominence: %w(requester_only hidden)).count
# => 10338
```

**Comment by RichardTaylor** [comment]
>At present [presumably on WhatDoTheyKnow] we have 10k+ requests where we're giving no explanation as to why the request is not visible to the average viewer.

Of those in how many cases do we actually have a recorded reason eg. not a FOI request, was personal correspondence, or was a subject access request?

Given this is in-public and readers can be concerned about us hiding material, and why we do so, it might be worth explaining that on WhatDoTheyKnow we very very rarely hide a substantive FOI request or response from public view. We operate a principle of minimising takedowns and if we have to remove material from a substantive request for information we will generally remove specific material from the thread, and explain what we have done and why, rather than remove the whole thread. 

We do remove whole threads in cases of misuse of our service eg. for general non-FOI correspondence, personal correspondence, or spam.  Another relatively small class of hidden requests are those which have been made by users evading a ban. 

We aspire to running the service even more transparently (there are various [related tickets](https://github.com/mysociety/alaveteli/labels/transparent-administration))

Over time more finely grained admin features have been added to the system. Where in the past our only option in a case might have been to remove a whole thread from public view, we can now remove specific material, and specific messages. Some of the reported hidden threads will be old. We reviewed, and republished, previously hidden threads in relation to substantive takedown cases when the more finely grained features were introduced. 

-- 

I want to repeat my caution about "activating" URLs for hidden or requester_only requests. We don't want to do that in relation to threads removed from public view due to personal correspondence, or for many types of misuse. 

-- 
If we've got substantive request specific content on a page should that page have a 4xx response code? It's then substantive material others might cite. 

--
My views remain in-line with my comment of 1 June https://github.com/mysociety/alaveteli/issues/6746#issuecomment-1143959442

**Comment by garethrees** [comment]
Linked to https://github.com/mysociety/alaveteli/issues/3090.

**Comment by garethrees** [comment]
> Given this is in-public and…

I don't think we need to justify this in the development tracker – it adds extra verbosity and confusion to threads. The place to do this is on-site help pages and blog posts, that can be linked to if we then get questions.

> Of those in how many cases do we actually have a recorded reason eg. not a FOI request, was personal correspondence, or was a subject access request?

The only "reason" we record at the `InfoRequest` level is the state, of which we only have "vexatious" and "not_foi". We don't have states for "personal correspondence", "SAR" etc – that's just "not_foi".

```ruby
InfoRequest.where(prominence: %w(requester_only hidden)).where(described_state: %w(vexatious not_foi)).count
# => 7483
```

That leaves 2855 requests with reduced prominence (excluding backpage) where we have no idea, without searching other systems, why the prominence was set to `hidden` or `requester_only`.

> I want to repeat my caution about "activating" URLs

I have no idea what you mean by this I'm afraid. All we're talking about here is including a `prominence_reason` field on `InfoRequest` and allowing it to be filled in on occasions that the reason for hiding something could do with elaboration in the same way that we use `prominence_reason` for outgoing and incoming messages.

**Comment by RichardTaylor** [comment]
I think perhaps what we need then is a practice/policy (and warning within the admin system) that any problematic material within the URL slug should be censored separately, and hiding a request alone is not sufficient for removing such material.

It is already the case that we treat request addresses for hidden requests differently from other /request/ URLs which don't lead to published requests (we show the "Request has been removed"). Adding request specific text to the page potentially makes the problem of keeping such URLs active worse. The URLs are already "active" to a degree, this proposal would make them more active, it would put content on them.

**Comment by garethrees** [comment]
> any problematic material within the URL slug should be censored separately, and hiding a request alone is not sufficient for removing such material.

Yeah, but this is already the case.

> this proposal would make them more active

I don't agree tbh – the URL is either active or its not.

If we want to completely "deactivate" a request URL we'd need to change the title (which would change the slug) or destroy the request.
