### ISSUE TITLE
Close and anonymise option is not available for banned users 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6872]
Is this by design or is it a bug?

Perhaps this is as usually we'll want to retain the email address of banned users to prevent them signing up for a new account under their email address. The feature could be available, but with a warning if this is the case?

**Comment by garethrees** [comment]
> Is this by design or is it a bug?

By design

> Perhaps this is as usually we'll want to retain the email address of banned users to prevent them signing up for a new account under their email address.

For this reason. Created https://github.com/mysociety/alaveteli/pull/6873 to make this clear.

> The feature could be available, but with a warning if this is the case?

It would mean a bunch of added complexity that feels unwarranted for this fairly edge-case situation.

* Would we fully anonymise, but need UI before/after the action to remind the admin that the address is now no longer banned?
* Would we anonymise _except_ the email address to preserve the ban? The automation might make it too easy to forget that the GDPR response needs to be tweaked to note the info we're preserving.
