### ISSUE TITLE
Show elements of public body notes on every request page

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#6920]
It might be useful for users if elements of public body notes were shown on every request page. 

As well as the manually set notes, tag driven notes such as: "This authority is not subject to FOI law, so is not legally obliged to respond" could be placed on request pages. 

This is the public body version of: "Show the requester's user profile on each request page" #6654

**Comment by garethrees** [comment]
Somewhat related to https://github.com/mysociety/alaveteli/issues/387

**Comment by lucascumsille** [comment]
I just made a mock-up of this feature, but I'd like to hear your thoughts first:

I moved the notes from the top, because, in terms of hierarchy, it doesn't seem like the main content of this page. However, let me know if you think it should be the first thing to be read when getting into this page.

I added a label for each note, in this case, "Note 1", "Note 2" and "Note 3", not sure if the notes will have a real ID that we can use instead( so users can reference notes with other team members).

https://user-images.githubusercontent.com/13790153/186835688-92ae9431-5235-427b-b632-828dadb47e0d.mov

<img width="1037" alt="Screenshot 2022-08-26 at 07 14 58" src="https://user-images.githubusercontent.com/13790153/186835706-f0783d51-8c7c-4912-b753-980fbb8fb4a6.png">
I a

**Comment by garethrees** [comment]
Couple of notes from our chat about this in standup (similar to the comments on the [body page](https://github.com/mysociety/alaveteli/issues/7240#issuecomment-1228298925) mockups):

* I don't think we want to use the "correspondence bubble" style for things that aren't exchanges between citizen and authority; We do have some existing styling for body notes when you go through to [make a request](https://www.whatdotheyknow.com/new/aberdeen_inspired) (the white box with green top border). We don't _have_ to use this styling, but it should certainly appear different to correspondence and more like an "attached note".
* Notes should be at the top on both body pages and request pages
* Styling of individual notes looks great – dividing line is good
* Not sure where the blue `Note 1` boxes will come from, as notes are currently just a single text/html attribute.
* Notes being collapsable isn't _essential_, but I appreciate that long notes might become a bit annoying.  I don't think notes should be _fully_ collapsible in the way that correspondence is – the implementation should _feel_ different to how it works for correspondence so that it's clear to the user that it's a _different_ concept in the UI. Perhaps a "show more"/"show less" link at the bottom of the note similar to our [refusal advice](https://www.whatdotheyknow.com/help/unhappy#refusal-advice) would work?

**Comment by garethrees** [comment]
Closing in favour of https://github.com/mysociety/alaveteli/issues/387, https://github.com/mysociety/alaveteli/issues/6912 and https://github.com/mysociety/alaveteli/issues/7240.
