### ISSUE TITLE
Option to use the body's url slug rather than name as the key when doing updates via the CSV upload

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7131]
We had a case today on WhatDoTheyKnow where someone sent in some body updates in a spreadsheet. They provided us with the accurate url slug for each body they wanted editing, but in some cases the names for the bodies in their spreadsheet differed from ours. 

I have no idea if this situation will be encountered again, I'm raising this ticket to log any future cases where this feature would have been useful.

**Comment by garethrees** [comment]
In some ways, kinda makes more sense than the ID since the slug is the visible public unique identifier.

Linking to https://github.com/mysociety/alaveteli/issues/4078#issuecomment-324264761 as this could be something to consider if it's rebuilt.

Going to close this for now as it's a niche issue, but if it reoccurs we can reopen.
