### ISSUE TITLE
Expected option for directing a reply not present

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7151]
When the requester clicks "write a reply" on 12 July on WhatDoTheyKnow request 860880 I expected them to have an option to send their reply to 

>foi (NHS BUCKINGHAMSHIRE, OXFORDSHIRE AND BERKSHIRE WEST ICB - 10Q), NHS Oxfordshire Clinical Commissioning Group

which is where the latest response in the thread came from, with the email address `bobicb-ox.foi@nhs.net`

In fact I expected that to be the default option. 

however the only options given were to write to

>the main FOI contact at NHS Oxfordshire Clinical Commissioning Group   (Default)

or

>FOI (NHS SOUTH, CENTRAL AND WEST COMMISSIONING SUPPORT UNIT)

Those both have different email addresses to each other and the one previously mentioned. 

I thought this could be due to the status "internal review", so I changed this to "waiting response" but that didn't change the options presented.

**Comment by mdeuk** [comment]
> When the requester clicks "write a reply" on 12 July on WhatDoTheyKnow request 860880 I expected them to have an option to send their reply to
> 
> > foi (NHS BUCKINGHAMSHIRE, OXFORDSHIRE AND BERKSHIRE WEST ICB - 10Q), NHS Oxfordshire Clinical Commissioning Group
> 
> which is where the latest response in the thread came from, with the email address `bobicb-ox.foi@nhs.net`

From WDTK Slack:

> I looked into that. It's awfully misleading - we sent it to the CCG address ([occg.foi@nhs.net](mailto:occg.foi@nhs.net)), which is seemingly mapping to [bobicb-ox.foi@nhs.net](mailto:bobicb-ox.foi@nhs.net). The 'ox' in the email suggests to me that they've done a 'lift and shift' of old CCG mailboxes and rebranded them. I presume it's because they have [reused ODS codes](https://digital.nhs.uk/services/organisation-data-service/integrated-care-boards/implementation-of-icbs-from-april-2022#what-is-changing-from-july-2022), and that there is some link between that and the NHSMail directory. Just an uninformed hypothesis mind you.

The actual email address for the successor body is [ever so slightly different](https://www.whatdotheyknow.com/body/nhs_buckinghamshire_oxfordshire_and_berkshire_west_integrated_care_board/view_email).

I think this is a niche situation where we've a public body take on the 'business' of its predecessor, but has then had to start the process of merging the assets of two bodies together, in a slightly unusual way. The confusing part is the naming - but that's coming from NHSMail rather than Alaveteli. I don't _think_ the system is doing anything wrong here; however my hypothesis could indeed be wrong itself.
