### ISSUE TITLE
Don't show categories where all members are defunct in Pro - "Add authorities to batch" system

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7176]

**Comment by RichardTaylor** [comment]
>This can be worked around without coding by putting the relevant category under a category of "defunct bodies".

Maybe not really, as defunct bodies should also be under their relevant "topic" classification eg. Health, Education etc.

**Comment by gbp** [comment]
Do you have a example category where all members are tagged 'defunct' ?

**Comment by RichardTaylor** [comment]
This can also be worked around by re-ordering category headings

https://github.com/mysociety/whatdotheyknow-theme/issues/1300

**Comment by gbp** [comment]
The CCG eg, https://www.whatdotheyknow.com/admin/bodies/51847 aren't tagged as `defunct` which is why they are still shown.

The `Police Authorities` category isn't shown in the batch category picker UI as all bodies within it are tagged `defunct`.

We [already hide](https://github.com/mysociety/alaveteli/blob/aed451b4247ac790350dfe23a8fbe667456e1ecc/app/models/public_body_category_link.rb#L58) categories with only non [requestable](https://github.com/mysociety/alaveteli/blob/aed451b4247ac790350dfe23a8fbe667456e1ecc/app/models/public_body.rb#L348-L350) authorities - see #6866. As far as I can see that is working so I'm going to close this issue but please reopen if I'm missing something.

**Comment by RichardTaylor** [comment]
>The CCG eg, https://www.whatdotheyknow.com/admin/bodies/51847 aren't tagged as defunct which is why they are still shown.

Sorry I thought we'd just marked them all as defunct as part of https://github.com/mysociety/whatdotheyknow-theme/issues/1022 - something went wrong with that which has now been sorted and they've gone from the batch category picker UI as expected.
