### ISSUE TITLE
Display number of working days passed since request was made

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/alaveteli#7228]
Tweet: https://twitter.com/adacable/status/1559652817018785795

>Feature request: Could you show "N working days ago" next to dates in your UI? It would make complaints and refering things to the ICO much easier.

Comment by @mdeuk via Slack:

>ou know, that's an interesting idea.
It might add a bit of UI clutter to present it by default - but if that was a concern then a tooltip or dropdown could be used - or the event log.

**Comment by mdeuk** [comment]
I would like to see this - the public holiday regimes aren't always the easiest for users to understand, for example, under [FoIA 2000 s10(6)(b)](https://www.legislation.gov.uk/ukpga/2000/36/section/10):

> “working day” means any day other than a Saturday, a Sunday, Christmas Day, Good Friday or a day which is a bank holiday under the Banking and Financial Dealings Act 1971 **_in any part of the United Kingdom_**. 

… the important part being the bit I have emphasised - a request can be delayed if there is a bank holiday in a part of the UK, even if it is no way related to the organisation in question (for example, a Civil Service agency in England could rely on a bank holiday in Northern Ireland or Scotland). Understanding the nuance can be difficult.

This is perhaps related to, but not a duplicate of, #5101 - I see both of them as serving different aims.

**Comment by adacable** [comment]
Oh hey this was my feature request, I didn't realise the development was this open. 

Looking through the code it seems like the kind of thing I can at least do some of the work on, though I'd appreciate guidance on how it should be styled, and which of the aproaches below are better:

In terms of styling: I think having it on a tooltip makes it harder to copy and paste into an email, which is undesirable. I think the simplest is brackets and n days ago inside the <time> element, though I'm open to other options. 

Do it in ruby:

I've got a vagrant build up and running, this is my current plan for implementation:
- Write out tests for a working_days_between(date1, date2), with the same test cases as exist for due_date_from_working_days (just, pick two dates 20 days apart)
- Write working_days_between to iterate between two days and count all the not holiday days
- Add a setting display_days_ago in the theme
- Put a "(n days ago)" text following the simple_date, inside the <time> tag, conditional on display_days_ago

I worry the above aproach could be quite slow- If a request has 20 messages from 10 years ago(far from an edge case), it's going to call weekend_or_holiday, which includes a database(or cache)lookup, 73,000 times. 

This seems like it may be a problem on even reasonably large or old requests- Possibly we could have it spit out "more than N months/years ago" once it's longer than three months, because at that stage the rhetotical point of "60 working days ago" is lacking anyway.

Do it in JS:

The other option is enclosing a list of holidays in a js file(ideally one preexisting to avoid another page load- maybe someone who knows the JS can suggest a suitable location?) and have a function which does the the holiday maths in JS. Even computing the 20 message/10 year request shouldn't be too long if it files on page load- They can run in paralell, and aren't blocking sending html or hitting any databases. 

I think doing it in JS leaves a basis for implementing #5101 quickly, but also means people with JS turned off are going to have a worse experience.

**Comment by garethrees** [comment]
@adacable hey 👋 thanks for thinking about this! I'll try to get back to you on some of the questions, though it might take a bit of time. I think figuring out the UI is the key thing to do first, as that'll have implications on how we approach the backend side.
