### ISSUE TITLE
Accept URLs without a leading http:// on body admin pages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7328]
I think 

https://github.com/mysociety/alaveteli/pull/7264  

has led to the body admin form requiring a leading `http://` on homepage URLs, whereas previously the system would accept, and deal properly with, URLs with or without that prefix. 

This ticket proposes returning the previous flexibility to optionally drop the `http://`

**Comment by mdeuk** [comment]
>This ticket proposes returning the previous flexibility to optionally drop the `http://`

Isn't this _**expected behaviour**_? An alternative fix for #7187 could involve server-side validation, but this doesn't seem massively problematic.

**Comment by RichardTaylor** [comment]
Presumably previously there is/was some server side code to deal with either www.example.com or http://www.example.com 

I thought the previous system in respect of accepting, and properly handling, either of those options was smart. 

The previous system was too lax with what it allowed in URL fields though.

**Comment by RichardTaylor** [comment]
I think I just had to add a "http://" to an existing homepage URL before I was able to save a change to a body.

**Comment by garethrees** [comment]
Closing as requiring valid URLs was intentional in https://github.com/mysociety/alaveteli/pull/7264.

It will affect some old records, but it's a small issue to add the protocol part of the domain.

For new records I'd imagine most input is via copy & paste to ensure the correct spelling, so the protocol should automatically get copied from the browser URL bar.
