### ISSUE TITLE
Remove thousands of real UK bodies from demo.alaveteli.org

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/alaveteli#7407]
There's no need for over 42 thousand real UK bodies appearing at 

https://demo.alaveteli.org/body/list/all

Perhaps there's no need for any real bodies?

While there doesn't appear to be a big problem with people making real requests on the demo site there does appear to be one

https://demo.alaveteli.org/request/fly_tipping_data_jan_2017_dec_20

Maybe also:

* ask search engines not to index the demo site (via meta-tags and/or robots.txt) ?
* add a banner to the demo site pointing to the real WhatDoTheyKnow

**Comment by garethrees** [comment]
> Perhaps there's no need for any real bodies?

Making up body names is time consuming. It's a tradeoff.

> There's no need for over 42 thousand real UK bodies appearing at…

There _was_ a need to have a large amount of bodies for a few reasons (demo, screencast, batch testing), and it was easier to write a script that imports everything rather than something more selective. Again, a tradeoff.

> add a banner to the demo site pointing to the real WhatDoTheyKnow

I've done this.

> ask search engines not to index the demo site

This would probably be worth doing, but much more fiddly. Unless we can set this header at the web server level, we'd have to figure out how to customise it at a theme level – but we often deploy "real" themes to demo for creating screenshots/screencasts/etc – or have to fork alaveteli/maintain a custom "demo" branch, none of which is worth the effort.

**Comment by RichardTaylor** [comment]
I wasn't aware of the scope of uses to which the demo site is put. 

I should note a concern here is that the demo site ends up competing with WDTK in search results. I don't know to what extent, if at all, having similar content on another site might detract from WDTK's listings in search engines. 

There is a more general "issue" of the WDTK bodies database appearing on a few sites now (it's openly licenced so this is permitted). It might not really be an issue, more just something of note.  At the moment I think WDTK is the only site using the bodies list containing substantive content.

**Comment by garethrees** [comment]
> I wasn't aware of the scope of uses to which the demo site is put.

No worries! I was just documenting why they're used.

> I should note a concern here…

Yep, valid concern.

> Unless we can set this header at the web server level

I figured out how to do this 🎉 

```
$ curl -I --silent https://demo.alaveteli.org?cache=nope | grep robots
x-robots-tag: noindex, noarchive, nosnippet, nofollow
```

I've also deployed this change to `staging.alaveteli.org`

```
$ curl -I --silent https://staging.alaveteli.org?cache=nope | grep robots
x-robots-tag: noindex, noarchive, nosnippet, nofollow
```
