### ISSUE TITLE
Add league tables to projects 

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#7542]
I was on a training call for volunteers who were being shown how to use projects to classify and extract data from a batch, and someone wanted to know if there way that they could track how many they had done, and see how that compared to others.

Gamification of the classification/data extraction process on a per project basis seems like it could be a good participation incentive. This could even be as simple as the league tables that we have for regular classification.

I know little about how projects works, so it is highly possible that this may already exist.

**Comment by garethrees** [comment]
It doesn't exist, though was certainly thought about. We've done this [manually](https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/37#issuecomment-639436029) at some point.

**Comment by garethrees** [comment]
found it!

```rb
project = Project.find(1)

csv_string = CSV.generate do |csv|
  csv << %w[name email classifications extractions user_created_at]

  project.members.each do |user|
    csv << [user.name,
      user.email,
      project.submissions.where(user_id: user.id).classification.size,
      project.submissions.where(user_id: user.id).extraction.size,
      user.created_at.to_date]
  end
end

File.write "tmp/project-#{project.id}-leaderboard.csv", csv_string
```

**Comment by HelenWDTK** [comment]
I think they'd love this doing manually if it's easy. They are having calls to classify/extract data together once a week, so that'd be a good time. There are 20, so a top 5 would probably be enough incentive.

**Comment by garethrees** [comment]
I got emailed privately about this for the specific partner context, which I've moved to an [internal thread](https://groups.google.com/a/mysociety.org/g/alaveteli/c/LJleFqoU4Cw/m/JDAD0EgwBAAJ) for wider team visibility. Would need to write slightly different code for a top 5, but the above gives a general sense of the main record relationships that need to be counted.

**Comment by garethrees** [comment]
I think this would be pretty easy to implement.

We could have an overall contributors leaderboard in the sidebar that just groups `Project::Submission` by user and counts them. I don't think it's worth having task-specific leaderboards as the first move.

<img width="492" alt="Screenshot 2023-01-24 at 15 07 33" src="https://user-images.githubusercontent.com/282788/214331184-62116845-4d8b-4916-913f-d5d0af08a994.png">

In terms of backend functionality I think it's pretty clear based on the above example and the [classification game league table](https://github.com/mysociety/alaveteli/blob/344a924da9c0fb767bd0e844cdd3e0cead4d64c9/app/controllers/request_game_controller.rb#L40-L42). We'd want to limit to top 5 users, and exclude those with zero contributions in the scoring.

As per the [categorisation game](https://www.whatdotheyknow.com/categorise/play), probably ought to link to the user account profile pages, but not _essential_.

**Comment by zarino** [comment]
Further comments from Hannah:

> We have one incredibly efficient volunteer who is head and shoulders over the rest to the extent where nobody has a chance of catching up, so it might be better for encouraging people if we could have a leaderboard for extractions for the last week rather than an accumulated total? Also if it lightens the load we can probably drop the classifications bit of the leaderboard as that will remain a trickle rather than a pour.

**Comment by garethrees** [comment]
Since we're continuing to manually extract the contributions data and we already have [the code](https://github.com/mysociety/alaveteli/issues/7542#issuecomment-1401698902) for it we should build a button for the _project owner_ to download this from the project homepage:

<img width="428" alt="Screenshot 2023-03-06 at 15 32 50" src="https://user-images.githubusercontent.com/282788/223156220-f6caf00a-917e-47d5-aa5a-e5fec15b53fe.png">

As for [the leaderboard](https://github.com/mysociety/alaveteli/issues/7542#issuecomment-1402106310), let's follow the [categorisation game](https://www.whatdotheyknow.com/categorise/play) [pattern](https://github.com/mysociety/alaveteli/blob/develop/app/models/statistics/leaderboard.rb) of "recent" (last 28 days) and "all time" (all contributions, scoped per project). I think this will be the most generally useful. Other projects might be a much slower pace than these, so weekly stats might not work so well.
