### ISSUE TITLE
Show (Account Suspended) next to the user's name on the request page when they've been banned

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/alaveteli#7850]
Previously (Account Suspended) was displayed next to a username on the profile and request pages. This no longer happens on request pages. This means it is much less obvious to other users of the service and admins that a user account has been banned.

**Comment by garethrees** [comment]
I think this only happens when we have a populated `OutgoingMessage#from_name` (rather than falling back to the user record).

## Option 1: Append to `InfoRequest#safe_from_name`

Could append this here:

```diff
diff --git a/app/models/info_request.rb b/app/models/info_request.rb
index 73b3b1039..9460a9a6b 100644
--- a/app/models/info_request.rb
+++ b/app/models/info_request.rb
@@ -766,6 +766,7 @@ def from_name

   def safe_from_name
     return external_user_name if is_external?
+    from_name << ' ' << _("(Account suspended)") if user.banned?
     apply_censor_rules_to_text(from_name)
   end
```

![Screenshot 2023-09-07 at 12 43 44](https://github.com/mysociety/alaveteli/assets/282788/b0cfff7c-0802-40c8-8ddb-7faa799612bc)

Not quite sure of the wider impact on adding this here. It shouldn't get written back to a name field on a record edit, but not sure.

## Option 2: Append to `OutgoingMessage#safe_from_name`

Similar to above…

```diff
diff --git a/app/models/outgoing_message.rb b/app/models/outgoing_message.rb
index 80a489226..6551b4006 100644
--- a/app/models/outgoing_message.rb
+++ b/app/models/outgoing_message.rb
@@ -144,6 +144,7 @@ def from_name

   def safe_from_name
     return info_request.external_user_name if info_request.is_external?
+    from_name << ' ' << _("(Account suspended)") if user.banned?
     info_request.apply_censor_rules_to_text(from_name)
   end
```

When `OutgoingMessage#from_name` is populated we then only get the notice on on the messages; not the request subtitle.

![Screenshot 2023-09-07 at 12 56 22](https://github.com/mysociety/alaveteli/assets/282788/12efae90-79e1-440a-8aa7-8c342d87cc03)

## Option 3: Add separate marker to request subtitle

Rather than mess around with the name, we could add a separate notice like:

```diff
diff --git a/app/views/request/_request_subtitle.html.erb b/app/views/request/_request_subtitle.html.erb
index 83b060e04..6f19cb345 100644
--- a/app/views/request/_request_subtitle.html.erb
+++ b/app/views/request/_request_subtitle.html.erb
@@ -8,6 +8,13 @@
                        user: user } %>
 <% end %>

+<% if info_request.user.banned? %>
+  <span class="request-header__foi_no">
+    <br>
+    <%= _('This user is suspended.') %>
+  </span>
+<% end %>
+
 <% if info_request.public_body.eir_only? %>
   <span class="request-header__foi_no">
     <br>
```

![Screenshot 2023-09-07 at 13 04 26](https://github.com/mysociety/alaveteli/assets/282788/074bbff6-2bf1-4901-827b-58522d50b064)

This could be as prominent as we want.

![Screenshot 2023-09-07 at 13 06 08](https://github.com/mysociety/alaveteli/assets/282788/c20e7f2b-61b7-4a28-9a1e-5e1574a1a2b0)

**Comment by HelenWDTK** [comment]
+1 This confused me again today when I thought we'd not correctly banned a user

**Comment by garethrees** [comment]
This is desirable, but unlikely to be worked on in the next 12 months so closing for now.
