### ISSUE TITLE
Uppercase characters in request email divert incoming message to holding pen

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#7902]
Here's a redacted but real example:

```
To: Request-[id]-[idhash]@Whatdotheyknow.Com
```

* Uppercase `R` of `Request`
* Uppercase `W` of `Whatdotheyknow`
* Uppercase `C` of `.Com`

We should do a case-insensitive comparison of these parts.

**Comment by alexander-griffen** [comment]
Writing tests expected to fail for this seem to pass, which implies that the issue may not be to do with cases (see attached PR)

**Comment by mdeuk** [comment]
> Writing tests expected to fail for this seem to pass, which implies that the issue may not be to do with cases (see attached PR)

Would it help to have a couple of the real world raw emails, to see if there's any _less obvious_ "funky formatting" at play?

**Comment by gbp** [comment]
> Would it help to have a couple of the real world raw emails, to see if there's any _less obvious_ "funky formatting" at play?

Yes please @mdeuk, it would be good to verify the issue with real examples and try workout if case-insensitivity is the issue or maybe there is another cause.

**Comment by mdeuk** [comment]
> Yes please @mdeuk, it would be good to verify the issue with real examples and try workout if case-insensitivity is the issue or maybe there is another cause.

No problem - I'll send you across an email with a couple of links in a minute. 👍

**Comment by gbp** [comment]
Thanks @mdeuk for the examples, having gone through this I think I've gone and understanding of what is happening. Basically both the `To` and `Received` have the address, one mixed case one down case. We don't get an exact match to a single request because we don't unique the requests - we can fix this easily but writing a failing spec is proving difficult.

Wondering if this has actually been fixed by #7790 as the guess mechanism works slightly different and it does return unique requests, so since Monday when WDTK got deployed with single guess redelivery, have their been any more cases of this issue?

**Comment by gbp** [comment]
This is definitely not an issue now we are checking the Message-ID headers in #7913
