### ISSUE TITLE
Account closure options redirect to main admin user profile, not edit page

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/alaveteli#7986]
When performing other edits, you would generally change all the fields as necessary, so this would perhaps be expected behaviour. However, admins will often be actioning multiple closure options in sequence, so having to click to go back into the edit page for a user takes slightly more time.

I think this is possibly a problem (in my experience) for certain other edit pages. For example, editing an attachment returns you to the incoming message's page. There may be others.

Ideally, the edit pages would redirect to themselves once the action is completed. This may not apply to all.

**Comment by garethrees** [comment]
Will keep this scoped to the following controllers so that it's an easy win:

* `AdminUsersAccountSuspensionsController`
* `AdminUsersAccountErasingController`
* `AdminUsersAccountClosingController`
* `AdminUsersAccountAnonymisingController`

**Comment by garethrees** [comment]
> Will keep this scoped to the following controllers so that it's an easy win:

In writing #8095 it transpired that it wouldn't make sense for `AdminUsersAccountSuspensionsController` to redirect to the edit action, as you enact it via the show page, so that's fine as is.

I left `AdminUsersAccountErasingController` redirect to show as it's the terminal action of a flow, so makes more sense to go back to show there and helps to visually distinguish the "end" state.
