### ISSUE TITLE
Add ability to embed individual documents from a response

### ISSUE THREAD

**Issue by henare** [mysociety/alaveteli#993]
I've noticed a number of media organisations uploading documents attached to Right To Know responses to Scribd so they can embed them in reports.

It would be great to be able to embed them right from the site so that it's easier for the person embedding and also to promote the Alaveteli-based site that the content is from, i.e. add a little link back to the site as Scribd does.

**Comment by RichardTaylor** [comment]
There is an example of a website embedding documents released via FOI using a Scribd like service "DocumentCloud" at 
https://theferret.scot/brexit-campaigners-spending/  (Paywall after three pages viewed currently).

In this case it's embedding a set of links to documents - rather than presenting the documents themselves under the media organisation's header an in the context of an article which Scribd enables. 

An option to embed a message, a request, and a document might be useful. 

This feature would provide media organisations an alternative method of citing material released via FOI. 

This feature might ideally be developed in conjunction with a media organisation that actually wants to use it.

**Comment by RichardTaylor** [comment]
This feature might help media organisations which don't want to prominently send users away from their website. 

Media organisations do use embeds, the BBC and newspaper websites in the UK often embed tweets. 

The option to embed a response email, and separately, an attachment would be good.
